name = "atomicFeaturesFormalization"
version = "0.1.0"
defaultTargets = ["PKG26AtomicFeatures", "AtomicFeatures", "SubmissionChecks"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true
weak.linter.unnecessarySimpa = false
weak.linter.unusedDecidableInType = false
weak.linter.unusedFintypeInType = false
weak.linter.unusedSectionVars = false
weak.linter.unusedVariables = false
weak.linter.flexible = false
weak.linter.style.longLine = false
weak.linter.style.whitespace = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "5450b53e5ddc75d46418fabb605edbf36bd0beb6"

[[lean_lib]]
name = "PKG26AtomicFeatures"

[[lean_lib]]
name = "AtomicFeatures"

[[lean_lib]]
name = "SubmissionChecks"
