import PKG26AtomicFeatures.SparseCoverCounting

/-!
# Concentration-profile and distinct-span refinements

This module strengthens the unconditional sparse-cover theorem in two ways.
First, it replaces the source spark cutoff by the exact maximum number of
source atoms that can concentrate in a subspace of a given dimension.  Second,
it counts distinct alternative column spans rather than syntactically distinct
supports that generate the same span.

These refinements apply to sparse factorizations without requiring
identifiable alternative dictionaries.
-/

namespace PKG26AtomicFeatures

open AppendixHall

/-- Source atoms contained in an arbitrary linear subspace. -/
noncomputable def sourceAtomsInSubmodule
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (subspace : Submodule ℝ (RepresentationVector d)) : Finset (Fin M) := by
  classical
  exact Finset.univ.filter fun i => (fun row => matrix row i) ∈ subspace

@[simp] theorem mem_sourceAtomsInSubmodule_iff
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (subspace : Submodule ℝ (RepresentationVector d)) (i : Fin M) :
    i ∈ sourceAtomsInSubmodule matrix subspace ↔
      (fun row => matrix row i) ∈ subspace := by
  classical
  simp [sourceAtomsInSubmodule]

/-- A source support whose column span lies in a subspace is contained in the
set of all source atoms lying in that subspace. -/
theorem source_support_subset_sourceAtomsInSubmodule
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    {sourceSupport : Finset (Fin M)}
    {subspace : Submodule ℝ (RepresentationVector d)}
    (hspan : columnSpan matrix sourceSupport ≤ subspace) :
    sourceSupport ⊆ sourceAtomsInSubmodule matrix subspace := by
  intro i hi
  rw [mem_sourceAtomsInSubmodule_iff]
  apply hspan
  apply Submodule.subset_span
  exact ⟨⟨i, hi⟩, rfl⟩

/-- The span of all source atoms contained in a subspace remains inside that
subspace. -/
theorem columnSpan_sourceAtomsInSubmodule_le
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (subspace : Submodule ℝ (RepresentationVector d)) :
    columnSpan matrix (sourceAtomsInSubmodule matrix subspace) ≤ subspace := by
  rw [columnSpan]
  apply Submodule.span_le.mpr
  rintro column ⟨coordinate, rfl⟩
  exact (mem_sourceAtomsInSubmodule_iff matrix subspace coordinate).mp coordinate.2

/-- A full-spark source dictionary realizes the uniform-matroid rank function:
the rank of every selected column family is the smaller of its cardinality and
the ambient dimension. -/
theorem finrank_columnSpan_eq_min_card_of_full_spark
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (hspark : spark matrix = d + 1) (vertices : Finset (Fin M)) :
    Module.finrank ℝ (columnSpan matrix vertices) = min vertices.card d := by
  classical
  by_cases hcard : vertices.card ≤ d
  · rw [Nat.min_eq_left hcard]
    simpa [columnSpan] using finrank_span_eq_card
      (linearIndependent_of_card_lt_spark matrix vertices (by
        rw [hspark]
        omega))
  · have hd_le_card : d ≤ vertices.card := by omega
    obtain ⟨selected, hselected_subset, hselected_card⟩ :=
      vertices.exists_subset_card_eq hd_le_card
    have hselected_independent :
        LinearIndependent ℝ (selectedColumns matrix selected) := by
      apply linearIndependent_of_card_lt_spark matrix selected
      rw [hspark, hselected_card]
      omega
    have hselected_rank :
        Module.finrank ℝ (columnSpan matrix selected) = d := by
      calc
        Module.finrank ℝ (columnSpan matrix selected) = selected.card := by
          simpa [columnSpan] using finrank_span_eq_card hselected_independent
        _ = d := hselected_card
    have hlower : d ≤ Module.finrank ℝ (columnSpan matrix vertices) := by
      calc
        d = Module.finrank ℝ (columnSpan matrix selected) := hselected_rank.symm
        _ ≤ Module.finrank ℝ (columnSpan matrix vertices) :=
          Submodule.finrank_mono (columnSpan_mono matrix hselected_subset)
    have hupper : Module.finrank ℝ (columnSpan matrix vertices) ≤ d := by
      simpa [RepresentationVector] using
        (Submodule.finrank_le (columnSpan matrix vertices))
    rw [Nat.min_eq_right hd_le_card]
    exact Nat.le_antisymm hupper hlower

/-- The largest rank of a source span generated by exactly `K` columns.
When `K ≤ M`, the indexing family is nonempty, so this finite supremum is the
literal maximum denoted by `ρ_K(A)` in the theorem-repair memo. -/
noncomputable def sourceSupportRankProfile
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) (K : ℕ) : ℕ := by
  classical
  exact ((Finset.univ : Finset (Finset (Fin M))).filter
    (fun support => support.card = K)).sup
      (fun support => Module.finrank ℝ (columnSpan matrix support))

/-- Every exact-`K` source support is bounded by the source rank profile. -/
theorem sourceSupport_finrank_le_sourceSupportRankProfile
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (support : Finset (Fin M)) (hsupport : support.card = K) :
    Module.finrank ℝ (columnSpan matrix support) ≤
      sourceSupportRankProfile matrix K := by
  classical
  unfold sourceSupportRankProfile
  exact Finset.le_sup
    (s := (Finset.univ : Finset (Finset (Fin M))).filter
      (fun selected => selected.card = K))
    (f := fun selected =>
      Module.finrank ℝ (columnSpan matrix selected))
    (b := support)
    (by simp [hsupport])

/-- A uniform upper bound on all exact-`K` source spans bounds their rank
profile.  This is the finite-max wrapper used to turn a pointwise rank theorem
into one scalar inequality. -/
theorem sourceSupportRankProfile_le_of_forall
    {d M K bound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (hbound : ∀ support : Finset (Fin M), support.card = K →
      Module.finrank ℝ (columnSpan matrix support) ≤ bound) :
    sourceSupportRankProfile matrix K ≤ bound := by
  classical
  apply Finset.sup_le
  intro support hsupport
  exact hbound support (Finset.mem_filter.mp hsupport).2

/-- Exact two-step rank expansion through the alternative neighborhood of a
source subcollection.  The source span embeds in the alternative neighborhood
span, whose rank is in turn bounded by its number of columns. -/
theorem sourceSubset_finrank_le_neighborhood_finrank_and_card_of_atom_supports
    {d M M' : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (supports : Fin M → Finset (Fin M'))
    (hatom : ∀ i : Fin M,
      (fun row => matrix row i) ∈ columnSpan alternative (supports i))
    (vertices : Finset (Fin M)) :
    Module.finrank ℝ (columnSpan matrix vertices) ≤
        Module.finrank ℝ
          (columnSpan alternative (neighborhood supports vertices)) ∧
      Module.finrank ℝ
          (columnSpan alternative (neighborhood supports vertices)) ≤
        (neighborhood supports vertices).card := by
  have hspan : columnSpan matrix vertices ≤
      columnSpan alternative (neighborhood supports vertices) := by
    rw [columnSpan]
    apply Submodule.span_le.mpr
    exact selectedColumns_subset_columnSpan_of_atom_supports
      matrix alternative supports hatom vertices
  exact ⟨Submodule.finrank_mono hspan,
    finrank_columnSpan_le_card alternative (neighborhood supports vertices)⟩

/-- Atomwise alternative supports obey the resulting cardinal rank-expansion
law on every source subcollection.  This is the lower Hall condition without
any independence or spark premise. -/
theorem sourceSubset_finrank_le_neighborhood_card_of_atom_supports
    {d M M' : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (supports : Fin M → Finset (Fin M'))
    (hatom : ∀ i : Fin M,
      (fun row => matrix row i) ∈ columnSpan alternative (supports i))
    (vertices : Finset (Fin M)) :
    Module.finrank ℝ (columnSpan matrix vertices) ≤
      (neighborhood supports vertices).card := by
  obtain ⟨hsource, halternative⟩ :=
    sourceSubset_finrank_le_neighborhood_finrank_and_card_of_atom_supports
      matrix alternative supports hatom vertices
  exact hsource.trans halternative

/-- The source concentration profile at dimension `rankBound`.

The finite definition maximizes over source-atom subsets whose own column span
has dimension at most `rankBound`.  This equals the geometric formulation that
maximizes the number of source atoms contained in an arbitrary subspace of
dimension at most `rankBound`; the upper direction is proved below and the
reverse direction is witnessed by the selected subset's own span. -/
noncomputable def sourceConcentration
    {d M : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (rankBound : ℕ) : ℕ :=
  ((Finset.univ : Finset (Fin M)).powerset).sup fun coordinates =>
    if Module.finrank ℝ (columnSpan matrix coordinates) ≤ rankBound then
      coordinates.card
    else 0

/-- Every atom subset whose span has bounded dimension is bounded by the
source concentration profile. -/
theorem card_le_sourceConcentration_of_finrank_columnSpan_le
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (coordinates : Finset (Fin M))
    (hrank : Module.finrank ℝ (columnSpan matrix coordinates) ≤ rankBound) :
    coordinates.card ≤ sourceConcentration matrix rankBound := by
  classical
  have hmem : coordinates ∈ (Finset.univ : Finset (Fin M)).powerset := by simp
  have hle := Finset.le_sup
    (f := fun selected : Finset (Fin M) =>
      if Module.finrank ℝ (columnSpan matrix selected) ≤ rankBound then
        selected.card
      else 0)
    hmem
  simpa [sourceConcentration, hrank] using hle

/-- The finite maximum defining the concentration profile is attained by a
source-atom subset of the prescribed rank. -/
theorem exists_sourceSupport_realizing_sourceConcentration
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    ∃ coordinates : Finset (Fin M),
      Module.finrank ℝ (columnSpan matrix coordinates) ≤ rankBound ∧
        coordinates.card = sourceConcentration matrix rankBound := by
  classical
  by_cases hzero : sourceConcentration matrix rankBound = 0
  · refine ⟨∅, ?_, by simp [hzero]⟩
    exact (finrank_columnSpan_le_card matrix ∅).trans (by simp)
  · have huniverse :
        ((Finset.univ : Finset (Fin M)).powerset).Nonempty := ⟨∅, by simp⟩
    obtain ⟨coordinates, _hcoordinates, hmax⟩ :=
      Finset.exists_mem_eq_sup
        ((Finset.univ : Finset (Fin M)).powerset) huniverse
        (fun selected =>
          if Module.finrank ℝ (columnSpan matrix selected) ≤ rankBound then
            selected.card
          else 0)
    have hprofile : sourceConcentration matrix rankBound =
        if Module.finrank ℝ (columnSpan matrix coordinates) ≤ rankBound then
          coordinates.card
        else 0 := by
      simpa [sourceConcentration] using hmax
    by_cases hrank :
        Module.finrank ℝ (columnSpan matrix coordinates) ≤ rankBound
    · refine ⟨coordinates, hrank, ?_⟩
      simpa [hrank] using hprofile.symm
    · have hprofile_zero : sourceConcentration matrix rankBound = 0 := by
        simpa [hrank] using hprofile
      exact (hzero hprofile_zero).elim

/-- The concentration profile always contains a block as large as its rank
budget, provided the source dictionary has at least that many columns. -/
theorem rankBound_le_sourceConcentration
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (hrankBound : rankBound ≤ M) :
    rankBound ≤ sourceConcentration matrix rankBound := by
  classical
  have hcard_univ : rankBound ≤ (Finset.univ : Finset (Fin M)).card := by
    simpa using hrankBound
  obtain ⟨coordinates, _hcoordinates, hcard⟩ :=
    (Finset.univ : Finset (Fin M)).exists_subset_card_eq hcard_univ
  rw [← hcard]
  apply card_le_sourceConcentration_of_finrank_columnSpan_le
  exact finrank_columnSpan_le_card matrix coordinates

/-- Below the source spark cutoff, no low-rank subspace can contain more
source atoms than its dimension. -/
theorem sourceConcentration_le_rankBound_of_succ_lt_spark
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (hcutoff : rankBound + 1 < spark matrix) :
    sourceConcentration matrix rankBound ≤ rankBound := by
  classical
  obtain ⟨coordinates, hrank, hcard⟩ :=
    exists_sourceSupport_realizing_sourceConcentration matrix
  rw [← hcard]
  by_contra hnot
  have hsucc_le_card : rankBound + 1 ≤ coordinates.card := by omega
  obtain ⟨selected, hselected_subset, hselected_card⟩ :=
    coordinates.exists_subset_card_eq hsucc_le_card
  have hselected_independent :
      LinearIndependent ℝ (selectedColumns matrix selected) := by
    apply linearIndependent_of_card_lt_spark
    simpa [hselected_card] using hcutoff
  have hselected_rank :
      Module.finrank ℝ (columnSpan matrix selected) = rankBound + 1 := by
    calc
      Module.finrank ℝ (columnSpan matrix selected) = selected.card := by
        simpa [columnSpan] using finrank_span_eq_card hselected_independent
      _ = rankBound + 1 := hselected_card
  have hmono : Module.finrank ℝ (columnSpan matrix selected) ≤
      Module.finrank ℝ (columnSpan matrix coordinates) :=
    Submodule.finrank_mono (columnSpan_mono matrix hselected_subset)
  omega

/-- The concentration profile is exactly the rank budget strictly below the
spark cutoff.  This recovers the full-spark identity `μ_A(r)=r` for `r<d`. -/
theorem sourceConcentration_eq_rankBound_of_succ_lt_spark
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (hcutoff : rankBound + 1 < spark matrix) :
    sourceConcentration matrix rankBound = rankBound := by
  apply Nat.le_antisymm
  · exact sourceConcentration_le_rankBound_of_succ_lt_spark matrix hcutoff
  · apply rankBound_le_sourceConcentration matrix
    have hspark_le := spark_le_column_count_succ matrix
    omega

/-- Geometric interpretation of the concentration profile: every subspace of
dimension at most `rankBound` contains at most the profiled number of source
atoms. -/
theorem sourceAtomsInSubmodule_card_le_sourceConcentration
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (subspace : Submodule ℝ (RepresentationVector d))
    (hrank : Module.finrank ℝ subspace ≤ rankBound) :
    (sourceAtomsInSubmodule matrix subspace).card ≤
      sourceConcentration matrix rankBound := by
  apply card_le_sourceConcentration_of_finrank_columnSpan_le
  exact (Submodule.finrank_mono
    (columnSpan_sourceAtomsInSubmodule_le matrix subspace)).trans hrank

/-- The finite profile exactly realizes the geometric maximum over subspaces:
some subspace of dimension at most `rankBound` contains precisely that many
source atoms. -/
theorem exists_submodule_realizing_sourceConcentration
    {d M rankBound : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    ∃ subspace : Submodule ℝ (RepresentationVector d),
      Module.finrank ℝ subspace ≤ rankBound ∧
        (sourceAtomsInSubmodule matrix subspace).card =
          sourceConcentration matrix rankBound := by
  obtain ⟨coordinates, hrank, hcard⟩ :=
    exists_sourceSupport_realizing_sourceConcentration matrix
  refine ⟨columnSpan matrix coordinates, hrank, ?_⟩
  have hsubset : coordinates ⊆
      sourceAtomsInSubmodule matrix (columnSpan matrix coordinates) :=
    source_support_subset_sourceAtomsInSubmodule matrix (hspan := le_rfl)
  have hlower := Finset.card_le_card hsubset
  have hupper := sourceAtomsInSubmodule_card_le_sourceConcentration
    matrix (columnSpan matrix coordinates) hrank
  omega

/-- Below the spark cutoff, two supports of the same cardinality cannot span
the same column space unless they are the same support.  Indeed, adjoining a
column from one support to the other would produce `width + 1` columns in a
space of rank at most `width`, contradicting independence below spark. -/
theorem columnSpan_eq_implies_eq_of_card_eq_of_succ_lt_spark
    {d M width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    {left right : Finset (Fin M)}
    (hleft : left.card = width) (hright : right.card = width)
    (hcutoff : width + 1 < spark matrix)
    (hspan : columnSpan matrix left = columnSpan matrix right) :
    left = right := by
  classical
  apply Finset.eq_of_subset_of_card_le
  · intro i hi
    by_contra hnot
    have hi_span : matrix.col i ∈ columnSpan matrix right := by
      rw [← hspan]
      apply Submodule.subset_span
      exact ⟨⟨i, hi⟩, rfl⟩
    let enlarged := insert i right
    have henlarged_card : enlarged.card = width + 1 := by
      simp [enlarged, hnot, hright]
    have henlarged_span : columnSpan matrix enlarged =
        columnSpan matrix right := by
      apply le_antisymm
      · rw [columnSpan]
        apply Submodule.span_le.mpr
        rintro column ⟨j, rfl⟩
        rcases Finset.mem_insert.mp j.2 with hji | hj
        · change matrix.col j.1 ∈ columnSpan matrix right
          rw [hji]
          exact hi_span
        · apply Submodule.subset_span
          exact ⟨⟨j.1, hj⟩, rfl⟩
      · exact columnSpan_mono matrix (Finset.subset_insert i right)
    have hli : LinearIndependent ℝ (selectedColumns matrix enlarged) :=
      linearIndependent_of_card_lt_spark matrix enlarged (by
        simpa [henlarged_card] using hcutoff)
    have hrank_enlarged :
        Module.finrank ℝ (columnSpan matrix enlarged) = width + 1 := by
      calc
        Module.finrank ℝ (columnSpan matrix enlarged) = enlarged.card := by
          simpa [columnSpan] using finrank_span_eq_card hli
        _ = width + 1 := henlarged_card
    have hrank_right :
        Module.finrank ℝ (columnSpan matrix right) ≤ width := by
      simpa [hright] using finrank_columnSpan_le_card matrix right
    rw [henlarged_span] at hrank_enlarged
    omega
  · omega

/-- The distinct subspaces generated by exactly `width` alternative columns. -/
noncomputable def distinctColumnSpans
    {d M' : ℕ} (alternative : Matrix (Fin d) (Fin M') ℝ)
    (width : ℕ) : Finset (Submodule ℝ (RepresentationVector d)) := by
  classical
  exact ((Finset.univ : Finset (Fin M')).powersetCard width).image
    (columnSpan alternative)

@[simp] theorem mem_distinctColumnSpans_iff
    {d M' width : ℕ} (alternative : Matrix (Fin d) (Fin M') ℝ)
    (subspace : Submodule ℝ (RepresentationVector d)) :
    subspace ∈ distinctColumnSpans alternative width ↔
      ∃ support : Finset (Fin M'),
        support.card = width ∧ columnSpan alternative support = subspace := by
  classical
  simp [distinctColumnSpans]

/-- Collapsing supports that generate the same subspace can only decrease the
number of alternative candidates. -/
theorem distinctColumnSpans_card_le_choose
    {d M' width : ℕ} (alternative : Matrix (Fin d) (Fin M') ℝ) :
    (distinctColumnSpans alternative width).card ≤ M'.choose width := by
  classical
  calc
    (distinctColumnSpans alternative width).card ≤
        ((Finset.univ : Finset (Fin M')).powersetCard width).card := by
      exact Finset.card_image_le
    _ = M'.choose width := by simp

/-- Below the spark cutoff, no two supports collapse to the same span, so the
number of distinct `width`-column spans is exactly the binomial coefficient. -/
theorem distinctColumnSpans_card_eq_choose_of_succ_lt_spark
    {d M' width : ℕ} (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hcutoff : width + 1 < spark alternative) :
    (distinctColumnSpans alternative width).card = M'.choose width := by
  classical
  calc
    (distinctColumnSpans alternative width).card =
        ((Finset.univ : Finset (Fin M')).powersetCard width).card := by
      rw [distinctColumnSpans, Finset.card_image_iff]
      intro left hleft right hright hspan
      exact columnSpan_eq_implies_eq_of_card_eq_of_succ_lt_spark
        alternative (Finset.mem_powersetCard.mp hleft).2
        (Finset.mem_powersetCard.mp hright).2 hcutoff hspan
    _ = M'.choose width := by simp

/-- Distinct source-atom incidence blocks induced by the alternative spans.
Two different alternative spans are identified here when they contain exactly
the same source atoms. -/
noncomputable def distinctSourceAtomBlocks
    {d M M' : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (width : ℕ) : Finset (Finset (Fin M)) := by
  classical
  exact (distinctColumnSpans alternative width).image
    (sourceAtomsInSubmodule matrix)

/-- Incidence blocks that can actually contain a source `K`-set.  Filtering
out smaller blocks loses no covering information and can strictly sharpen the
block-count bound. -/
noncomputable def activeSourceAtomBlocks
    {d M M' : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (width K : ℕ) : Finset (Finset (Fin M)) := by
  classical
  exact (distinctSourceAtomBlocks matrix alternative width).filter
    (fun block => K ≤ block.card)

@[simp] theorem mem_activeSourceAtomBlocks_iff
    {d M M' width K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (block : Finset (Fin M)) :
    block ∈ activeSourceAtomBlocks matrix alternative width K ↔
      block ∈ distinctSourceAtomBlocks matrix alternative width ∧
        K ≤ block.card := by
  classical
  simp [activeSourceAtomBlocks]

/-- Passing from alternative spans to their source-atom incidence blocks can
only identify candidates. -/
theorem distinctSourceAtomBlocks_card_le_distinctColumnSpans
    {d M M' width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ) :
    (distinctSourceAtomBlocks matrix alternative width).card ≤
      (distinctColumnSpans alternative width).card := by
  classical
  exact Finset.card_image_le

/-- Discarding incidence blocks too small to contain a source `K`-set can only
decrease the family cardinality. -/
theorem activeSourceAtomBlocks_card_le_distinctSourceAtomBlocks
    {d M M' width K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ) :
    (activeSourceAtomBlocks matrix alternative width K).card ≤
      (distinctSourceAtomBlocks matrix alternative width).card := by
  classical
  exact Finset.card_le_card (Finset.filter_subset _ _)

/-- A bounded covering family for all source `K`-subsets. -/
def IsCoveringFamily (M width K : ℕ)
    (family : Finset (Finset (Fin M))) : Prop :=
  (∀ block ∈ family, block.card ≤ width) ∧
    ∀ subset ∈ (Finset.univ : Finset (Fin M)).powersetCard K,
      ∃ block ∈ family, subset ⊆ block

/-- Blocks smaller than the covered-set size have zero covering capacity and
may be removed without changing the covering property. -/
theorem active_filter_isCoveringFamily
    {M width K : ℕ} (family : Finset (Finset (Fin M)))
    (hfamily : IsCoveringFamily M width K family) :
    IsCoveringFamily M width K
      (family.filter fun block => K ≤ block.card) := by
  classical
  constructor
  · intro block hblock
    exact hfamily.1 block (Finset.mem_filter.mp hblock).1
  · intro subset hsubset
    obtain ⟨block, hblock, hsubset_block⟩ := hfamily.2 subset hsubset
    have hK_le_block : K ≤ block.card := by
      have hcard := Finset.card_le_card hsubset_block
      rw [(Finset.mem_powersetCard.mp hsubset).2] at hcard
      exact hcard
    exact ⟨block, Finset.mem_filter.mpr ⟨hblock, hK_le_block⟩,
      hsubset_block⟩

/-- All bounded covering families on an `M`-element source universe. -/
noncomputable def coveringFamilies (M width K : ℕ) :
    Finset (Finset (Finset (Fin M))) := by
  classical
  exact ((Finset.univ : Finset (Fin M)).powerset.powerset).filter
    (IsCoveringFamily M width K)

@[simp] theorem mem_coveringFamilies_iff
    {M width K : ℕ} (family : Finset (Finset (Fin M))) :
    family ∈ coveringFamilies M width K ↔ IsCoveringFamily M width K family := by
  classical
  simp [coveringFamilies, IsCoveringFamily]

/-- The finite covering number `C(M,width,K)`.  If no bounded cover exists,
the totalized value is zero; every application below constructs a cover first,
so it always uses the genuine minimum branch. -/
noncomputable def coveringNumber (M width K : ℕ) : ℕ :=
  let cards := (coveringFamilies M width K).image Finset.card
  if h : cards.Nonempty then cards.min' h else 0

/-- Any exhibited bounded cover upper-bounds the covering number. -/
theorem coveringNumber_le_card_of_coveringFamily
    {M width K : ℕ} (family : Finset (Finset (Fin M)))
    (hfamily : IsCoveringFamily M width K family) :
    coveringNumber M width K ≤ family.card := by
  classical
  let cards := (coveringFamilies M width K).image Finset.card
  have hfamily_mem : family ∈ coveringFamilies M width K :=
    (mem_coveringFamilies_iff family).2 hfamily
  have hcard_mem : family.card ∈ cards :=
    Finset.mem_image.mpr ⟨family, hfamily_mem, rfl⟩
  have hnonempty : cards.Nonempty := ⟨family.card, hcard_mem⟩
  change (if h : cards.Nonempty then cards.min' h else 0) ≤ family.card
  rw [dif_pos hnonempty]
  exact Finset.min'_le cards family.card hcard_mem

/-- The elementary binomial lower bound for any bounded covering family. -/
theorem choose_le_coveringFamily_card_mul_choose
    {M width K : ℕ} (family : Finset (Finset (Fin M)))
    (hfamily : IsCoveringFamily M width K family) :
    M.choose K ≤ family.card * width.choose K := by
  let sourceUniverse : Finset (Fin M) := Finset.univ
  have hcount := choose_le_card_mul_choose_of_powersetCard_cover
    sourceUniverse family id K width hfamily.1 hfamily.2
  simpa [sourceUniverse] using hcount

/-- Exact incidence-weighted lower bound for a covering family.  It retains
each block's actual capacity instead of replacing every block by one common
worst-case width. -/
theorem choose_le_sum_coveringFamily_block_choose
    {M width K : ℕ} (family : Finset (Finset (Fin M)))
    (hfamily : IsCoveringFamily M width K family) :
    M.choose K ≤ ∑ block ∈ family, block.card.choose K := by
  let sourceUniverse : Finset (Fin M) := Finset.univ
  have hsubset : sourceUniverse.powersetCard K ⊆
      family.biUnion (fun block => block.powersetCard K) := by
    intro subset hsubset_source
    obtain ⟨block, hblock, hsubset_block⟩ :=
      hfamily.2 subset hsubset_source
    exact Finset.mem_biUnion.mpr
      ⟨block, hblock, Finset.mem_powersetCard.mpr
        ⟨hsubset_block, (Finset.mem_powersetCard.mp hsubset_source).2⟩⟩
  calc
    M.choose K = (sourceUniverse.powersetCard K).card := by
      simp [sourceUniverse]
    _ ≤ (family.biUnion (fun block => block.powersetCard K)).card :=
      Finset.card_le_card hsubset
    _ ≤ ∑ block ∈ family, (block.powersetCard K).card :=
      Finset.card_biUnion_le
    _ = ∑ block ∈ family, block.card.choose K := by simp

/-- A bounded covering family's exact block-capacity sum is at most its
cardinality times the common worst-case binomial capacity. -/
theorem sum_coveringFamily_block_choose_le_card_mul_choose
    {M width K : ℕ} (family : Finset (Finset (Fin M)))
    (hfamily : IsCoveringFamily M width K family) :
    (∑ block ∈ family, block.card.choose K) ≤
      family.card * width.choose K := by
  calc
    (∑ block ∈ family, block.card.choose K) ≤
        ∑ _block ∈ family, width.choose K := by
      apply Finset.sum_le_sum
      intro block hblock
      exact Nat.choose_le_choose K (hfamily.1 block hblock)
    _ = family.card * width.choose K := by simp

/-- Distinct alternative spans induce a concentration-bounded family that
covers every source `K`-set whenever every source `K`-span is contained in an
alternative span generated by at most `width` columns. -/
theorem distinctColumnSpanBlocks_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    IsCoveringFamily M (sourceConcentration matrix width) K
      (distinctSourceAtomBlocks matrix alternative width) := by
  classical
  unfold distinctSourceAtomBlocks
  constructor
  · intro block hblock
    obtain ⟨subspace, hsubspace, rfl⟩ := Finset.mem_image.mp hblock
    apply sourceAtomsInSubmodule_card_le_sourceConcentration
    obtain ⟨support, hsupport_card, hsupport_span⟩ :=
      (mem_distinctColumnSpans_iff alternative subspace).mp hsubspace
    rw [← hsupport_span]
    exact (finrank_columnSpan_le_card alternative support).trans_eq hsupport_card
  · intro sourceSupport hsourceSupport
    obtain ⟨smallSupport, hsmallSupport_card, hspan⟩ :=
      hcover sourceSupport (Finset.mem_powersetCard.mp hsourceSupport).2
    have hwidth_univ : width ≤ (Finset.univ : Finset (Fin M')).card := by
      simpa using hwidth_le
    obtain ⟨support, hsmallSupport_subset, hsupport_card⟩ :=
      Finset.exists_superset_card_eq hsmallSupport_card hwidth_univ
    let subspace := columnSpan alternative support
    have hsubspace : subspace ∈ distinctColumnSpans alternative width := by
      apply (mem_distinctColumnSpans_iff alternative subspace).2
      exact ⟨support, hsupport_card, rfl⟩
    refine ⟨sourceAtomsInSubmodule matrix subspace,
      Finset.mem_image.mpr ⟨subspace, hsubspace, rfl⟩, ?_⟩
    apply source_support_subset_sourceAtomsInSubmodule matrix
    exact hspan.trans (columnSpan_mono alternative hsmallSupport_subset)

/-- Exact local rank consequence of a sparse subspace cover.  No spark or
general-position premise is needed: every source `K`-span has rank at most the
alternative width.  Thus part (a)'s `K` lower bound needs only one independent
source `K`-set, rather than independence of every such set. -/
theorem sourceSupport_finrank_le_width_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      Module.finrank ℝ (columnSpan matrix sourceSupport) ≤ width := by
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, halternative_card, hspan⟩ :=
    hcover sourceSupport hsourceSupport
  exact (Submodule.finrank_mono hspan).trans
    ((finrank_columnSpan_le_card alternative alternativeSupport).trans
      halternative_card)

/-- The same local argument also remembers the rank of the entire alternative
dictionary.  This can be strictly sharper than the column-count bound when
the alternative matrix has redundant atoms. -/
theorem sourceSupport_finrank_le_min_width_alternativeRank_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      Module.finrank ℝ (columnSpan matrix sourceSupport) ≤
        min width (Module.finrank ℝ (columnSpan alternative Finset.univ)) := by
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, halternative_card, hspan⟩ :=
    hcover sourceSupport hsourceSupport
  exact (Nat.le_min).2 ⟨
    (Submodule.finrank_mono hspan).trans
      ((finrank_columnSpan_le_card alternative alternativeSupport).trans
        halternative_card),
    (Submodule.finrank_mono hspan).trans
      (Submodule.finrank_mono
        (columnSpan_mono alternative (Finset.subset_univ alternativeSupport)))⟩

/-- If `K` is positive and no larger than the source atom count, covering all
source `K`-spans forces the entire source dictionary span into the entire
alternative dictionary span. -/
theorem full_source_span_le_full_alternative_span_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    columnSpan matrix Finset.univ ≤ columnSpan alternative Finset.univ := by
  rw [columnSpan]
  apply Submodule.span_le.mpr
  rintro sourceColumn ⟨sourceIndex, rfl⟩
  have hsingleton_card :
      ({sourceIndex.1} : Finset (Fin M)).card ≤ K := by
    simp
    omega
  obtain ⟨sourceSupport, hsingleton_subset, _hsource_univ,
      hsource_card⟩ :=
    Finset.exists_subsuperset_card_eq
      (Finset.subset_univ ({sourceIndex.1} : Finset (Fin M)))
      hsingleton_card (by simpa using hK_le_M)
  obtain ⟨alternativeSupport, _halternative_card, hspan⟩ :=
    hcover sourceSupport hsource_card
  have hsource_mem : (fun row => matrix row sourceIndex.1) ∈
      columnSpan matrix sourceSupport := by
    apply Submodule.subset_span
    exact ⟨⟨sourceIndex.1,
      hsingleton_subset (Finset.mem_singleton_self sourceIndex.1)⟩, rfl⟩
  have halternative_mem := hspan hsource_mem
  have hfull_mem :=
    (columnSpan_mono alternative (Finset.subset_univ alternativeSupport))
      halternative_mem
  simpa [selectedColumns] using hfull_mem

/-- Positive sparse-plane coverage compares the two dictionary ranks directly,
before weakening the alternative rank to its number of columns. -/
theorem source_dictionary_rank_le_alternative_rank_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    Module.finrank ℝ (columnSpan matrix Finset.univ) ≤
      Module.finrank ℝ (columnSpan alternative Finset.univ) := by
  exact Submodule.finrank_mono
    (full_source_span_le_full_alternative_span_of_sparse_subspace_cover
      matrix alternative hKpos hK_le_M hcover)

/-- Rank floor implied by a sparse subspace cover: a positive source richness
level forces at least the source dictionary rank many alternative atoms. -/
theorem source_dictionary_rank_le_alternative_atom_count_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    Module.finrank ℝ (columnSpan matrix Finset.univ) ≤ M' := by
  exact (Submodule.finrank_mono
    (full_source_span_le_full_alternative_span_of_sparse_subspace_cover
      matrix alternative hKpos hK_le_M hcover)).trans
    ((finrank_columnSpan_le_card alternative Finset.univ).trans_eq (by simp))

/-- The active incidence blocks still cover every source `K`-set and obey the
same source-concentration cap. -/
theorem activeSourceAtomBlocks_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    IsCoveringFamily M (sourceConcentration matrix width) K
      (activeSourceAtomBlocks matrix alternative width K) := by
  unfold activeSourceAtomBlocks
  exact active_filter_isCoveringFamily _
    (distinctColumnSpanBlocks_cover matrix alternative hwidth_le hcover)

/-- Exact covering-number lower bound on the number of distinct alternative
spans. -/
theorem coveringNumber_le_distinctColumnSpans_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    coveringNumber M (sourceConcentration matrix width) K ≤
      (distinctColumnSpans alternative width).card := by
  let family := (distinctColumnSpans alternative width).image
    (sourceAtomsInSubmodule matrix)
  have hminimum := coveringNumber_le_card_of_coveringFamily family
    (distinctColumnSpanBlocks_cover matrix alternative hwidth_le hcover)
  exact hminimum.trans Finset.card_image_le

/-- The covering number is already bounded by the number of distinct
source-atom incidence blocks, which can be smaller than the number of distinct
alternative spans. -/
theorem coveringNumber_le_distinctSourceAtomBlocks_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    coveringNumber M (sourceConcentration matrix width) K ≤
      (distinctSourceAtomBlocks matrix alternative width).card := by
  exact coveringNumber_le_card_of_coveringFamily _
    (distinctColumnSpanBlocks_cover matrix alternative hwidth_le hcover)

/-- The covering number is bounded by only the positive-capacity incidence
blocks; empty and undersized blocks do not enter the count. -/
theorem coveringNumber_le_activeSourceAtomBlocks_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    coveringNumber M (sourceConcentration matrix width) K ≤
      (activeSourceAtomBlocks matrix alternative width K).card := by
  exact coveringNumber_le_card_of_coveringFamily _
    (activeSourceAtomBlocks_cover matrix alternative hwidth_le hcover)

/-- Strongest finite incidence inequality in this module: every source
`K`-set is charged to an actual distinct source-atom block, retaining the
individual binomial capacity of each block. -/
theorem choose_le_sum_distinctSourceAtomBlocks_choose_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    M.choose K ≤
      ∑ block ∈ distinctSourceAtomBlocks matrix alternative width,
        block.card.choose K := by
  exact choose_le_sum_coveringFamily_block_choose _
    (distinctColumnSpanBlocks_cover matrix alternative hwidth_le hcover)

/-- Exact incidence-weighted bound after deleting every block with zero
`K`-set capacity. -/
theorem choose_le_sum_activeSourceAtomBlocks_choose_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    M.choose K ≤
      ∑ block ∈ activeSourceAtomBlocks matrix alternative width K,
        block.card.choose K := by
  exact choose_le_sum_coveringFamily_block_choose _
    (activeSourceAtomBlocks_cover matrix alternative hwidth_le hcover)

/-- Worst-case concentration upper bound for the active block-capacity sum. -/
theorem sum_activeSourceAtomBlocks_choose_le_card_mul_concentration_choose
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    (∑ block ∈ activeSourceAtomBlocks matrix alternative width K,
        block.card.choose K) ≤
      (activeSourceAtomBlocks matrix alternative width K).card *
        (sourceConcentration matrix width).choose K := by
  exact sum_coveringFamily_block_choose_le_card_mul_choose _
    (activeSourceAtomBlocks_cover matrix alternative hwidth_le hcover)

/-- Replacing the heterogeneous block capacities by the worst-case
concentration profile upper-bounds the weighted incidence sum. -/
theorem sum_distinctSourceAtomBlocks_choose_le_card_mul_concentration_choose
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    (∑ block ∈ distinctSourceAtomBlocks matrix alternative width,
        block.card.choose K) ≤
      (distinctSourceAtomBlocks matrix alternative width).card *
        (sourceConcentration matrix width).choose K := by
  exact sum_coveringFamily_block_choose_le_card_mul_choose _
    (distinctColumnSpanBlocks_cover matrix alternative hwidth_le hcover)

/-- Worst-case concentration consequence using the number of distinct
incidence blocks, which is never larger than the number of distinct spans. -/
theorem choose_le_distinctSourceAtomBlocks_mul_concentration_choose
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    M.choose K ≤
      (distinctSourceAtomBlocks matrix alternative width).card *
        (sourceConcentration matrix width).choose K := by
  exact (choose_le_sum_distinctSourceAtomBlocks_choose_of_sparse_subspace_cover
    matrix alternative hwidth_le hcover).trans
      (sum_distinctSourceAtomBlocks_choose_le_card_mul_concentration_choose
        matrix alternative hwidth_le hcover)

/-- The concentration profile yields a sharper numerical inequality because it
counts distinct alternative spans and their actual source-atom capacity. -/
theorem choose_le_distinctColumnSpans_mul_concentration_choose
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    M.choose K ≤ (distinctColumnSpans alternative width).card *
      (sourceConcentration matrix width).choose K := by
  let family := (distinctColumnSpans alternative width).image
    (sourceAtomsInSubmodule matrix)
  have hfamily := distinctColumnSpanBlocks_cover matrix alternative hwidth_le hcover
  have hcount := choose_le_coveringFamily_card_mul_choose family hfamily
  exact hcount.trans (Nat.mul_le_mul_right _ Finset.card_image_le)

/-- Complete concentration-profile sandwich for an abstract sparse subspace
cover: the covering number is bounded by the number of distinct alternative
spans, which is in turn bounded by the number of alternative supports. -/
theorem concentration_profile_bounds_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    coveringNumber M (sourceConcentration matrix width) K ≤
        (distinctColumnSpans alternative width).card ∧
      (distinctColumnSpans alternative width).card ≤ M'.choose width := by
  exact ⟨coveringNumber_le_distinctColumnSpans_of_sparse_subspace_cover
    matrix alternative hwidth_le hcover,
    distinctColumnSpans_card_le_choose alternative⟩

/-- Refined covering-number chain.  The middle incidence-block count
identifies distinct alternative spans that contain exactly the same source
atoms, and is therefore never larger than the distinct-span count. -/
theorem concentration_profile_chain_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    coveringNumber M (sourceConcentration matrix width) K ≤
        (distinctSourceAtomBlocks matrix alternative width).card ∧
      (distinctSourceAtomBlocks matrix alternative width).card ≤
        (distinctColumnSpans alternative width).card ∧
      (distinctColumnSpans alternative width).card ≤ M'.choose width := by
  exact ⟨
    coveringNumber_le_distinctSourceAtomBlocks_of_sparse_subspace_cover
      matrix alternative hwidth_le hcover,
    distinctSourceAtomBlocks_card_le_distinctColumnSpans matrix alternative,
    distinctColumnSpans_card_le_choose alternative⟩

/-- Sharpest checked cardinality chain: retain only incidence blocks large
enough to cover a source `K`-set before comparing with all incidence blocks,
distinct spans, and syntactic alternative supports. -/
theorem concentration_active_block_chain_of_sparse_subspace_cover
    {d M M' K width : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (hwidth_le : width ≤ M')
    (hcover : ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      ∃ alternativeSupport : Finset (Fin M'),
        alternativeSupport.card ≤ width ∧
          columnSpan matrix sourceSupport ≤
            columnSpan alternative alternativeSupport) :
    coveringNumber M (sourceConcentration matrix width) K ≤
        (activeSourceAtomBlocks matrix alternative width K).card ∧
      (activeSourceAtomBlocks matrix alternative width K).card ≤
        (distinctSourceAtomBlocks matrix alternative width).card ∧
      (distinctSourceAtomBlocks matrix alternative width).card ≤
        (distinctColumnSpans alternative width).card ∧
      (distinctColumnSpans alternative width).card ≤ M'.choose width := by
  exact ⟨
    coveringNumber_le_activeSourceAtomBlocks_of_sparse_subspace_cover
      matrix alternative hwidth_le hcover,
    activeSourceAtomBlocks_card_le_distinctSourceAtomBlocks matrix alternative,
    distinctSourceAtomBlocks_card_le_distinctColumnSpans matrix alternative,
    distinctColumnSpans_card_le_choose alternative⟩

/-- Positive source richness and two sparse factorizations produce bounded
atom supports with the exact two-step rank law on every source subcollection:
the source rank is bounded by the rank of the corresponding alternative
neighborhood, which is bounded by that neighborhood's cardinality. -/
theorem exists_rank_expanding_atom_supports_with_alternative_rank_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    ∃ supports : Fin M → Finset (Fin M'),
      (∀ i, (supports i).card ≤ min K' M') ∧
        ∀ vertices : Finset (Fin M),
          Module.finrank ℝ (columnSpan matrix vertices) ≤
              Module.finrank ℝ
                (columnSpan alternative (neighborhood supports vertices)) ∧
            Module.finrank ℝ
                (columnSpan alternative (neighborhood supports vertices)) ≤
              (neighborhood supports vertices).card := by
  classical
  have hsupport_exists : ∀ i : Fin M,
      ∃ support : Finset (Fin M'),
        support.card ≤ min K' M' ∧
          (fun row => matrix row i) ∈ columnSpan alternative support := by
    intro i
    have hsingleton_card : ({i} : Finset (Fin M)).card ≤ K := by
      simp
      omega
    obtain ⟨sourceSupport, hsingleton_subset, _hsource_univ,
        hsource_card⟩ :=
      Finset.exists_subsuperset_card_eq
        (Finset.subset_univ ({i} : Finset (Fin M)))
        hsingleton_card (by simpa using hK_le_M)
    obtain ⟨alternativeSupport, hspan⟩ :=
      exists_sparse_alternative_subspace_containing_coordinate_image
        matrix z f alternative alternativeCode hrich hfactors
        (kSparse_min_columnCount alternativeCode halternativeSparse)
        halternativeFactors sourceSupport hsource_card
    have hcolumnSpan : columnSpan matrix sourceSupport ≤
        columnSpan alternative alternativeSupport.1 := by
      rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
      exact hspan
    refine ⟨alternativeSupport.1, alternativeSupport.2, hcolumnSpan ?_⟩
    apply Submodule.subset_span
    exact ⟨⟨i, hsingleton_subset (Finset.mem_singleton_self i)⟩, rfl⟩
  choose supports hsupports_card hatom using hsupport_exists
  refine ⟨supports, hsupports_card, ?_⟩
  intro vertices
  exact sourceSubset_finrank_le_neighborhood_finrank_and_card_of_atom_supports
    matrix alternative supports hatom vertices

/-- Cardinality consequence of the exact rank-expanding support theorem.
These supports need not be compatible across source `K`-planes, but every
source subcollection has rank at most the size of their union. -/
theorem exists_rank_expanding_atom_supports_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    ∃ supports : Fin M → Finset (Fin M'),
      (∀ i, (supports i).card ≤ min K' M') ∧
        ∀ vertices : Finset (Fin M),
          Module.finrank ℝ (columnSpan matrix vertices) ≤
            (neighborhood supports vertices).card := by
  obtain ⟨supports, hsupports_card, hrank⟩ :=
    exists_rank_expanding_atom_supports_with_alternative_rank_of_kRich_and_factorizations
      matrix z f alternative alternativeCode hKpos hK_le_M hrich hfactors
        halternativeSparse halternativeFactors
  refine ⟨supports, hsupports_card, ?_⟩
  intro vertices
  exact (hrank vertices).1.trans (hrank vertices).2

/-- Full spark specializes the rank-expansion law to truncated Hall expansion:
every source subcollection has at least `min |I| d` alternative neighbors.
This follows from the displayed model assumptions alone; what they do not
provide is the complementary `K`-local upper bound used by the appendix. -/
theorem exists_full_spark_expanding_atom_supports_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hspark : spark matrix = d + 1)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    ∃ supports : Fin M → Finset (Fin M'),
      (∀ i, (supports i).card ≤ min K' M') ∧
        ∀ vertices : Finset (Fin M),
          min vertices.card d ≤ (neighborhood supports vertices).card := by
  obtain ⟨supports, hsupports_card, hrank⟩ :=
    exists_rank_expanding_atom_supports_of_kRich_and_factorizations
      matrix z f alternative alternativeCode hKpos hK_le_M hrich hfactors
        halternativeSparse halternativeFactors
  refine ⟨supports, hsupports_card, ?_⟩
  intro vertices
  rw [← finrank_columnSpan_eq_min_card_of_full_spark matrix hspark vertices]
  exact hrank vertices

/-- Source-model local-rank theorem.  Every source `K`-span has rank at most
the effective alternative sparsity `min K' M'`, directly from richness and the
two factorizations. -/
theorem sourceSupport_finrank_le_effective_alternative_sparsity
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      Module.finrank ℝ (columnSpan matrix sourceSupport) ≤ min K' M' := by
  apply sourceSupport_finrank_le_width_of_sparse_subspace_cover
    matrix alternative
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Rank-aware strengthening of the source-model local bound.  Every source
`K`-span has rank at most both the declared alternative sparsity and the rank
of the entire alternative dictionary. -/
theorem sourceSupport_finrank_le_min_alternativeSparsity_rank
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    ∀ sourceSupport : Finset (Fin M), sourceSupport.card = K →
      Module.finrank ℝ (columnSpan matrix sourceSupport) ≤
        min K' (Module.finrank ℝ (columnSpan alternative Finset.univ)) := by
  intro sourceSupport hsourceSupport
  have hbound :=
    sourceSupport_finrank_le_min_width_alternativeRank_of_sparse_subspace_cover
      (width := min K' M') matrix alternative (K := K) (by
        intro selected hselected
        obtain ⟨alternativeSupport, hspan⟩ :=
          exists_sparse_alternative_subspace_containing_coordinate_image
            matrix z f alternative alternativeCode hrich hfactors
            (kSparse_min_columnCount alternativeCode halternativeSparse)
            halternativeFactors selected hselected
        refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
        rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
        exact hspan) sourceSupport hsourceSupport
  exact hbound.trans
    (min_le_min_right _ (Nat.min_le_left K' M'))

/-- Scalar rank-profile form of the local rank theorem.  The maximum rank of
an exact source `K`-span is bounded simultaneously by alternative sparsity and
alternative dictionary rank. -/
theorem sourceSupportRankProfile_le_min_alternativeSparsity_rank
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    sourceSupportRankProfile matrix K ≤
      min K' (Module.finrank ℝ (columnSpan alternative Finset.univ)) := by
  apply sourceSupportRankProfile_le_of_forall
  exact sourceSupport_finrank_le_min_alternativeSparsity_rank
    matrix z f alternative alternativeCode hrich hfactors
      halternativeSparse halternativeFactors

/-- Part (a) under its minimal transparent rank premise: it is enough that
one source `K`-set is independent.  Full spark, or even independence of every
source `K`-set, is unnecessary. -/
theorem source_sparsity_le_effective_alternative_sparsity_of_exists_independent_support
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hindependent : ∃ sourceSupport : Finset (Fin M),
      sourceSupport.card = K ∧
        LinearIndependent ℝ (selectedColumns matrix sourceSupport))
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    K ≤ min K' M' := by
  obtain ⟨sourceSupport, hsource_card, hindependent⟩ := hindependent
  have hrank : Module.finrank ℝ (columnSpan matrix sourceSupport) = K := by
    calc
      Module.finrank ℝ (columnSpan matrix sourceSupport) =
          sourceSupport.card := by
        simpa [columnSpan] using finrank_span_eq_card hindependent
      _ = K := hsource_card
  rw [← hrank]
  exact sourceSupport_finrank_le_effective_alternative_sparsity
    matrix z f alternative alternativeCode hrich hfactors
      halternativeSparse halternativeFactors sourceSupport hsource_card

/-- One independent source `K`-set also forces the alternative dictionary
itself to have rank at least `K`; redundant alternative atoms cannot substitute
for independent directions. -/
theorem source_sparsity_le_min_alternativeSparsity_rank_of_exists_independent_support
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hindependent : ∃ sourceSupport : Finset (Fin M),
      sourceSupport.card = K ∧
        LinearIndependent ℝ (selectedColumns matrix sourceSupport))
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    K ≤ min K' (Module.finrank ℝ
      (columnSpan alternative Finset.univ)) := by
  obtain ⟨sourceSupport, hsource_card, hindependent⟩ := hindependent
  have hrank : Module.finrank ℝ (columnSpan matrix sourceSupport) = K := by
    calc
      Module.finrank ℝ (columnSpan matrix sourceSupport) =
          sourceSupport.card := by
        simpa [columnSpan] using finrank_span_eq_card hindependent
      _ = K := hsource_card
  rw [← hrank]
  exact sourceSupport_finrank_le_min_alternativeSparsity_rank
    matrix z f alternative alternativeCode hrich hfactors
      halternativeSparse halternativeFactors sourceSupport hsource_card

/-- Exact full-spark scalar form of part (a), including the dimension-limited
regime: a source richness level `K` forces effective alternative rank-sparsity
at least `min K d`. -/
theorem min_sourceSparsity_dimension_le_min_alternativeSparsity_rank_full_spark
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hspark : spark matrix = d + 1) (hK_le_M : K ≤ M)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    min K d ≤ min K' (Module.finrank ℝ
      (columnSpan alternative Finset.univ)) := by
  classical
  have hcard : K ≤ (Finset.univ : Finset (Fin M)).card := by
    simpa using hK_le_M
  obtain ⟨sourceSupport, _hsubset, hsource_card⟩ :=
    Finset.exists_subset_card_eq hcard
  have hbound := sourceSupport_finrank_le_min_alternativeSparsity_rank
    matrix z f alternative alternativeCode hrich hfactors
      halternativeSparse halternativeFactors sourceSupport hsource_card
  rw [finrank_columnSpan_eq_min_card_of_full_spark matrix hspark sourceSupport,
    hsource_card] at hbound
  exact hbound

/-- Source-model rank floor.  At every positive richness level no larger than
the source width, the alternative dictionary has at least the rank of the
full source dictionary. -/
theorem source_dictionary_rank_le_alternative_atom_count_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    Module.finrank ℝ (columnSpan matrix Finset.univ) ≤ M' := by
  apply source_dictionary_rank_le_alternative_atom_count_of_sparse_subspace_cover
    (width := min K' M') matrix alternative hKpos hK_le_M
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Source-model rank monotonicity: positive richness makes the span of the
source dictionary a subspace of the span of the alternative dictionary, so
the source rank is bounded by the alternative rank, not merely by its width. -/
theorem source_dictionary_rank_le_alternative_rank_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    Module.finrank ℝ (columnSpan matrix Finset.univ) ≤
      Module.finrank ℝ (columnSpan alternative Finset.univ) := by
  apply source_dictionary_rank_le_alternative_rank_of_sparse_subspace_cover
    (width := min K' M') matrix alternative hKpos hK_le_M
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Under source full spark, every positive rich factorization forces the
alternative dictionary to have full ambient rank.  This records the complete
linear-algebra chain `d ≤ rank(A') ≤ M'`, stronger than the width-only floor. -/
theorem full_spark_alternative_rank_bounds_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hspark : spark matrix = d + 1)
    (hKpos : 0 < K) (hK_le_M : K ≤ M)
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    d ≤ Module.finrank ℝ (columnSpan alternative Finset.univ) ∧
      Module.finrank ℝ (columnSpan alternative Finset.univ) ≤ M' := by
  have hsource_rank :
      Module.finrank ℝ (columnSpan matrix Finset.univ) = d := by
    rw [finrank_columnSpan_eq_min_card_of_full_spark matrix hspark]
    simp only [Finset.card_univ, Fintype.card_fin]
    exact Nat.min_eq_right
      (ambient_dimension_le_column_count_of_spark_eq matrix hspark)
  have hrank :=
    source_dictionary_rank_le_alternative_rank_of_kRich_and_factorizations
      matrix z f alternative alternativeCode hKpos hK_le_M hrich hfactors
        halternativeSparse halternativeFactors
  rw [hsource_rank] at hrank
  refine ⟨hrank, ?_⟩
  simpa using finrank_columnSpan_le_card alternative
    (Finset.univ : Finset (Fin M'))

/-- Source-model concentration theorem.  Richness and the two sparse
factorizations alone give the exact covering-number sandwich at the effective
alternative width `min K' M'`; no spark, full-rank, or support-compatibility
premise is used. -/
theorem concentration_profile_bounds_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    coveringNumber M (sourceConcentration matrix (min K' M')) K ≤
        (distinctColumnSpans alternative (min K' M')).card ∧
      (distinctColumnSpans alternative (min K' M')).card ≤
        M'.choose (min K' M') := by
  apply concentration_profile_bounds_of_sparse_subspace_cover
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Numerical companion to the exact covering-number sandwich. -/
theorem concentration_choose_bound_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    M.choose K ≤
      (distinctColumnSpans alternative (min K' M')).card *
        (sourceConcentration matrix (min K' M')).choose K := by
  apply choose_le_distinctColumnSpans_mul_concentration_choose
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Source-model wrapper for the refined covering-number chain. -/
theorem concentration_profile_chain_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    coveringNumber M (sourceConcentration matrix (min K' M')) K ≤
        (distinctSourceAtomBlocks matrix alternative (min K' M')).card ∧
      (distinctSourceAtomBlocks matrix alternative (min K' M')).card ≤
        (distinctColumnSpans alternative (min K' M')).card ∧
      (distinctColumnSpans alternative (min K' M')).card ≤
        M'.choose (min K' M') := by
  apply concentration_profile_chain_of_sparse_subspace_cover
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Source-model wrapper for the active-block cardinality chain.  Incidence
blocks too small to cover a source `K`-set are deleted before any count is
taken. -/
theorem concentration_active_block_chain_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    coveringNumber M (sourceConcentration matrix (min K' M')) K ≤
        (activeSourceAtomBlocks matrix alternative (min K' M') K).card ∧
      (activeSourceAtomBlocks matrix alternative (min K' M') K).card ≤
        (distinctSourceAtomBlocks matrix alternative (min K' M')).card ∧
      (distinctSourceAtomBlocks matrix alternative (min K' M')).card ≤
        (distinctColumnSpans alternative (min K' M')).card ∧
      (distinctColumnSpans alternative (min K' M')).card ≤
        M'.choose (min K' M') := by
  apply concentration_active_block_chain_of_sparse_subspace_cover
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Source-model wrapper for the exact incidence-weighted capacity bound. -/
theorem weighted_distinct_block_bound_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    M.choose K ≤
      ∑ block ∈ distinctSourceAtomBlocks matrix alternative (min K' M'),
        block.card.choose K := by
  apply choose_le_sum_distinctSourceAtomBlocks_choose_of_sparse_subspace_cover
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Source-model wrapper for the exact active-block capacity bound. -/
theorem weighted_active_block_bound_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    M.choose K ≤
      ∑ block ∈ activeSourceAtomBlocks matrix alternative (min K' M') K,
        block.card.choose K := by
  apply choose_le_sum_activeSourceAtomBlocks_choose_of_sparse_subspace_cover
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

/-- Source-model wrapper for the active-block worst-case concentration bound. -/
theorem concentration_active_block_choose_bound_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    M.choose K ≤
      (activeSourceAtomBlocks matrix alternative (min K' M') K).card *
        (sourceConcentration matrix (min K' M')).choose K := by
  exact (weighted_active_block_bound_of_kRich_and_factorizations
    matrix z f alternative alternativeCode hrich hfactors
      halternativeSparse halternativeFactors).trans
    (by
      apply sum_activeSourceAtomBlocks_choose_le_card_mul_concentration_choose
        matrix alternative (Nat.min_le_right _ _)
      intro sourceSupport hsourceSupport
      obtain ⟨alternativeSupport, hspan⟩ :=
        exists_sparse_alternative_subspace_containing_coordinate_image
          matrix z f alternative alternativeCode hrich hfactors
          (kSparse_min_columnCount alternativeCode halternativeSparse)
          halternativeFactors sourceSupport hsourceSupport
      refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
      rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
      exact hspan)

/-- Source-model wrapper for the worst-case concentration bound using the
sharper distinct-incidence-block count. -/
theorem concentration_block_choose_bound_of_kRich_and_factorizations
    {X : Type*} {d M M' K K' : ℕ}
    (matrix : Matrix (Fin d) (Fin M) ℝ)
    (z : X → FeatureVector M) (f : X → RepresentationVector d)
    (alternative : Matrix (Fin d) (Fin M') ℝ)
    (alternativeCode : X → FeatureVector M')
    (hrich : KRich (K := K) z)
    (hfactors : ∀ x, f x = matrix.mulVec (z x))
    (halternativeSparse : KSparse (K := K') alternativeCode)
    (halternativeFactors : ∀ x,
      f x = alternative.mulVec (alternativeCode x)) :
    M.choose K ≤
      (distinctSourceAtomBlocks matrix alternative (min K' M')).card *
        (sourceConcentration matrix (min K' M')).choose K := by
  apply choose_le_distinctSourceAtomBlocks_mul_concentration_choose
    matrix alternative (Nat.min_le_right _ _)
  intro sourceSupport hsourceSupport
  obtain ⟨alternativeSupport, hspan⟩ :=
    exists_sparse_alternative_subspace_containing_coordinate_image
      matrix z f alternative alternativeCode hrich hfactors
      (kSparse_min_columnCount alternativeCode halternativeSparse)
      halternativeFactors sourceSupport hsourceSupport
  refine ⟨alternativeSupport.1, alternativeSupport.2, ?_⟩
  rw [← map_mulVecLin_coordinateSpan_eq_columnSpan]
  exact hspan

end PKG26AtomicFeatures
