import PKG26AtomicFeatures.DictionaryModel

/-!
# Dimension-limited sharpness template

This module formalizes the general identity-dictionary obstruction discussed
in the Codex theorem-repair memo.  For any source matrix, take as the source
domain all `K`-sparse coefficient vectors.  Its image is automatically
factorized by the `d`-column identity dictionary with sparsity `d`.  Hence any
full-spark overcomplete source matrix with `d = K + 1` realizes a strict width
reduction at exactly the corrected `K + 1` threshold.  When `2 ≤ K`, the same
template lies below the proposed `2*K` threshold because `d < 2*K`.

This is a formalizer-proposed sharpness result, not a source theorem.  It is
fully exact and uses no continuity, choice of contextual supports, or
certificate-shaped computation.
-/

namespace PKG26AtomicFeatures

/-- The domain of all coefficient vectors with support size at most `K`. -/
abbrev UniversalSparseDomain (M K : ℕ) :=
  {v : FeatureVector M // (nonzeroSupport v).card ≤ K}

/-- Inclusion of the universal sparse domain into coefficient space. -/
def universalSparseCode {M K : ℕ} :
    UniversalSparseDomain M K → FeatureVector M :=
  Subtype.val

theorem universalSparseCode_sparse {M K : ℕ} :
    KSparse (K := K) (universalSparseCode (M := M) (K := K)) :=
  fun x => x.2

/-- The universal sparse domain is exactly rich, not merely dense, on every
`K`-coordinate subspace. -/
theorem universalSparseCode_rich {M K : ℕ} :
    KRich (K := K) (universalSparseCode (M := M) (K := K)) := by
  intro coordinates hcoordinates v hv
  have hsupport := nonzeroSupport_subset_of_mem_coordinateSpan hv
  have hsparse : (nonzeroSupport v).card ≤ K := by
    calc
      (nonzeroSupport v).card ≤ coordinates.card :=
        Finset.card_le_card hsupport
      _ = K := hcoordinates
  exact subset_closure ⟨⟨v, hsparse⟩, rfl⟩

/-- Representations generated by a source matrix on the universal sparse
domain. -/
def universalSparseRepresentation
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    UniversalSparseDomain M K → RepresentationVector d :=
  fun x => matrix.mulVec x.1

def universalSparseSourceDictionary
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    Dictionary (UniversalSparseDomain M K) d M K where
  matrix := matrix
  code := universalSparseCode
  sparse := universalSparseCode_sparse

theorem universalSparseSource_factors
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    Factors (universalSparseSourceDictionary (K := K) matrix)
      (universalSparseRepresentation (K := K) matrix) :=
  fun _ => rfl

/-- The identity alternative uses each generated representation as its own
coordinate code. -/
def identityAlternativeDictionary
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    Dictionary (UniversalSparseDomain M K) d d d where
  matrix := 1
  code := universalSparseRepresentation (K := K) matrix
  sparse := representation_is_dimension_sparse
    (universalSparseRepresentation (K := K) matrix)

theorem identityAlternative_factors
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ) :
    Factors (identityAlternativeDictionary (K := K) matrix)
      (universalSparseRepresentation (K := K) matrix) := by
  intro x
  simp [identityAlternativeDictionary]

/-- General sharpness template for the corrected strict-width conclusion.

If a full-spark overcomplete source matrix has ambient dimension `K + 1`, its
universal `K`-rich factorization admits a strictly narrower identity
factorization with sparsity exactly `K + 1`.  Thus no theorem covering this
regime can replace the corrected successor lower bound by a larger universal
integer threshold. -/
theorem identity_dictionary_attains_successor_threshold
    {d M K : ℕ} (matrix : Matrix (Fin d) (Fin M) ℝ)
    (hspark : spark matrix = d + 1)
    (hdimension : d = K + 1)
    (hovercomplete : d < M) :
    spark matrix = d + 1 ∧
      KRich (K := K) (universalSparseCode (M := M) (K := K)) ∧
      Factors (universalSparseSourceDictionary (K := K) matrix)
        (universalSparseRepresentation (K := K) matrix) ∧
      Factors (identityAlternativeDictionary (K := K) matrix)
        (universalSparseRepresentation (K := K) matrix) ∧
      d < M ∧ d = K + 1 := by
  exact ⟨hspark, universalSparseCode_rich,
    universalSparseSource_factors (K := K) matrix,
    identityAlternative_factors (K := K) matrix, hovercomplete, hdimension⟩

/-- For `K ≥ 2`, the sharp identity template also lies strictly below the
printed `2*K` threshold. -/
theorem successor_dimension_lt_two_mul
    {d K : ℕ} (hK : 2 ≤ K) (hdimension : d = K + 1) :
    d < 2 * K := by
  omega

end PKG26AtomicFeatures
