import PKG26AtomicFeatures.SignedLineGeometry
import PKG26AtomicFeatures.SparseSubspaceIncidence
import Mathlib.Analysis.Normed.Module.Normalize

/-!
# Normalized child directions modulo a parent

The parent line is removed by its actual orthogonal projector. Both the
source and learned projected children are then normalized. Close parent
lines preserve a lower bound on the learned projected norm; close matched
parent-child planes control the angle between the normalized projections.
No unnormalized projected inner product is asserted to approach one.
-/

namespace PKG26AtomicFeatures

open scoped InnerProductSpace

/-- The child vector after removing the parent line. -/
noncomputable def quotientChildVector {n : ℕ}
    (parent child : EuclideanRepresentation n) : EuclideanRepresentation n :=
  (ℝ ∙ parent)ᗮ.starProjection child

/-- The repaired quotient direction normalizes the projected child.
The geometric theorems below prove that the projected vector is nonzero. -/
noncomputable def normalizedQuotientChild {n : ℕ}
    (parent child : EuclideanRepresentation n) : EuclideanRepresentation n :=
  NormedSpace.normalize (quotientChildVector parent child)

/-- A residual bound to the line of a unit vector controls absolute cosine
and distance to one of its two orientations. -/
theorem unit_directions_bounds_of_line_residual {n : ℕ}
    (u v : EuclideanRepresentation n) (hu : ‖u‖ = 1) (hv : ‖v‖ = 1)
    (r : ℝ) (hres : ‖(ℝ ∙ u)ᗮ.starProjection v‖ ≤ r) :
    1 - r ^ 2 ≤ |inner ℝ u v| ∧
      (‖u - v‖ ≤ 2 * r ∨ ‖u + v‖ ≤ 2 * r) := by
  have hr : 0 ≤ r := (norm_nonneg _).trans hres
  have hsq : ‖(ℝ ∙ u)ᗮ.starProjection v‖ ^ 2 = 1 - (inner ℝ u v) ^ 2 := by
    rw [Submodule.starProjection_orthogonal_val,
      Submodule.starProjection_unit_singleton ℝ hu, norm_sub_sq_real,
      norm_smul, Real.norm_eq_abs, real_inner_smul_right, hu, hv, real_inner_comm v u]
    simp only [one_pow, mul_one, sq_abs]
    ring
  have hc : |inner ℝ u v| ≤ 1 := by
    simpa only [hu, hv, mul_one] using abs_real_inner_le_norm u v
  have hprod := mul_nonneg (abs_nonneg (inner ℝ u v)) (sub_nonneg.mpr hc)
  have hres_sq := mul_self_le_mul_self (norm_nonneg _) hres
  rw [← sq, ← sq, hsq] at hres_sq
  have habs : 1 - r ^ 2 ≤ |inner ℝ u v| := by nlinarith [sq_abs (inner ℝ u v)]
  refine ⟨habs, ?_⟩
  by_cases hsign : 0 ≤ inner ℝ u v
  · left
    rw [abs_of_nonneg hsign] at habs
    have hdist := norm_sub_sq_real u v
    rw [hu, hv] at hdist
    nlinarith [sq_nonneg r, norm_nonneg (u - v)]
  · right
    rw [abs_of_neg (lt_of_not_ge hsign)] at habs
    have hdist := norm_add_sq_real u v
    rw [hu, hv] at hdist
    nlinarith [sq_nonneg r, norm_nonneg (u + v)]

/-- Close parent lines change the projection of a unit child by at most
the parent projector gap. -/
theorem quotientChildVector_distance_le_parent_gap {n : ℕ}
    (a b d : EuclideanRepresentation n) (hd : ‖d‖ = 1) (δP : ℝ)
    (hgap : ‖(ℝ ∙ a).starProjection - (ℝ ∙ b).starProjection‖ ≤ δP) :
    ‖quotientChildVector a d - quotientChildVector b d‖ ≤ δP := by
  have hpoint := ((ℝ ∙ a).starProjection - (ℝ ∙ b).starProjection).le_opNorm d
  rw [ContinuousLinearMap.sub_apply, hd, mul_one] at hpoint
  have heq : quotientChildVector a d - quotientChildVector b d =
      -((ℝ ∙ a).starProjection d - (ℝ ∙ b).starProjection d) := by
    simp only [quotientChildVector, Submodule.starProjection_orthogonal_val]
    abel
  rw [heq, norm_neg]
  exact hpoint.trans hgap

/-- The plane generated by a parent and child projects into the line of
the normalized projected child. This is also valid if the child projection
vanishes, in which case both projected spaces are zero. -/
theorem quotientChildVector_mem_normalized_line_of_mem_pair {n : ℕ}
    (a c x : EuclideanRepresentation n)
    (hx : x ∈ Submodule.span ℝ ({a, c} : Set (EuclideanRepresentation n))) :
    quotientChildVector a x ∈ ℝ ∙ normalizedQuotientChild a c := by
  obtain ⟨s, t, rfl⟩ := Submodule.mem_span_pair.mp hx
  have hzero : (ℝ ∙ a)ᗮ.starProjection a = 0 :=
    Submodule.starProjection_orthogonalComplement_singleton_eq_zero a
  simp only [quotientChildVector, map_add, map_smul, hzero, smul_zero, zero_add]
  apply (ℝ ∙ normalizedQuotientChild a c).smul_mem
  have hmem := (ℝ ∙ normalizedQuotientChild a c).smul_mem
    ‖quotientChildVector a c‖
    (Submodule.mem_span_singleton_self (normalizedQuotientChild a c))
  simpa only [normalizedQuotientChild, NormedSpace.norm_smul_normalize] using hmem

/-- The learned child, projected off the true parent, has line residual
at most the matched-plane projector gap. -/
theorem quotientChildVector_line_residual_le_plane_gap {n : ℕ}
    (a c b d : EuclideanRepresentation n) (hd : ‖d‖ = 1) (δS : ℝ)
    (hgap : ‖(Submodule.span ℝ ({a, c} : Set (EuclideanRepresentation n))).starProjection -
      (Submodule.span ℝ ({b, d} : Set (EuclideanRepresentation n))).starProjection‖ ≤ δS) :
    ‖(ℝ ∙ normalizedQuotientChild a c)ᗮ.starProjection (quotientChildVector a d)‖ ≤ δS := by
  have hdmem : d ∈ Submodule.span ℝ ({b, d} : Set (EuclideanRepresentation n)) :=
    Submodule.subset_span (by simp)
  have hreverse : ‖(Submodule.span ℝ ({b, d} : Set (EuclideanRepresentation n))).starProjection -
      (Submodule.span ℝ ({a, c} : Set (EuclideanRepresentation n))).starProjection‖ ≤ δS := by
    simpa only [norm_sub_rev] using hgap
  obtain ⟨x, hx, hdx⟩ := directed_subspace_approximation_of_projector_bound _ _ δS
    hreverse d hdmem
  rw [hd, mul_one] at hdx
  have hline := norm_orthogonal_projection_le_sub_of_mem
    (ℝ ∙ normalizedQuotientChild a c) (quotientChildVector a d) (quotientChildVector a x)
      (quotientChildVector_mem_normalized_line_of_mem_pair a c x hx)
  have hcontract := (ℝ ∙ a)ᗮ.norm_starProjection_apply_le (d - x)
  simp only [map_sub] at hcontract
  exact hline.trans (hcontract.trans hdx)

/-- Parent and parent-child plane recovery imply normalized child recovery
modulo the true parent. The learned projected norm is at least `γ-δP>0`;
the absolute cosine error is at most `(δS/(γ-δP))²`. -/
theorem normalized_quotient_child_recovery {n : ℕ}
    (a c b d : EuclideanRepresentation n)
    (hunit : ‖a‖ = 1 ∧ ‖c‖ = 1 ∧ ‖b‖ = 1 ∧ ‖d‖ = 1)
    (γ δP δS : ℝ) (hγ : 0 < γ) (hsmall : δP < γ)
    (hsource : γ ≤ ‖quotientChildVector a c‖)
    (hlearned : γ ≤ ‖quotientChildVector b d‖)
    (hparent : ‖(ℝ ∙ a).starProjection - (ℝ ∙ b).starProjection‖ ≤ δP)
    (hplane : ‖(Submodule.span ℝ ({a, c} : Set (EuclideanRepresentation n))).starProjection -
      (Submodule.span ℝ ({b, d} : Set (EuclideanRepresentation n))).starProjection‖ ≤ δS) :
    quotientChildVector a c ≠ 0 ∧ quotientChildVector a d ≠ 0 ∧
      γ - δP ≤ ‖quotientChildVector a d‖ ∧
      ‖normalizedQuotientChild a c‖ = 1 ∧ ‖normalizedQuotientChild a d‖ = 1 ∧
      1 - (δS / (γ - δP)) ^ 2 ≤
        |inner ℝ (normalizedQuotientChild a c) (normalizedQuotientChild a d)| ∧
      (‖normalizedQuotientChild a c - normalizedQuotientChild a d‖ ≤ 2 * (δS / (γ - δP)) ∨
        ‖normalizedQuotientChild a c + normalizedQuotientChild a d‖ ≤ 2 * (δS / (γ - δP))) := by
  have hδS : 0 ≤ δS := (norm_nonneg _).trans hplane
  have hden : 0 < γ - δP := sub_pos.mpr hsmall
  have hdiff := quotientChildVector_distance_le_parent_gap a b d hunit.2.2.2 δP hparent
  have hlower : γ - δP ≤ ‖quotientChildVector a d‖ := by
    have hnorm := norm_sub_norm_le (quotientChildVector b d) (quotientChildVector a d)
    rw [norm_sub_rev (quotientChildVector b d)] at hnorm
    linarith
  have hsource_ne : quotientChildVector a c ≠ 0 := norm_pos_iff.mp (hγ.trans_le hsource)
  have htarget_ne : quotientChildVector a d ≠ 0 := norm_pos_iff.mp (hden.trans_le hlower)
  have hsunit : ‖normalizedQuotientChild a c‖ = 1 := NormedSpace.norm_normalize hsource_ne
  have htunit : ‖normalizedQuotientChild a d‖ = 1 := NormedSpace.norm_normalize htarget_ne
  have hraw := quotientChildVector_line_residual_le_plane_gap a c b d hunit.2.2.2 δS hplane
  have hnormalized : ‖(ℝ ∙ normalizedQuotientChild a c)ᗮ.starProjection
      (normalizedQuotientChild a d)‖ ≤ δS / (γ - δP) := by
    calc
      _ = ‖(ℝ ∙ normalizedQuotientChild a c)ᗮ.starProjection
          (quotientChildVector a d)‖ / ‖quotientChildVector a d‖ := by
        change ‖(ℝ ∙ normalizedQuotientChild a c)ᗮ.starProjection
          (‖quotientChildVector a d‖⁻¹ • quotientChildVector a d)‖ = _
        rw [map_smul, norm_smul,
          Real.norm_eq_abs, abs_of_nonneg (inv_nonneg.mpr (norm_nonneg _))]
        rw [div_eq_mul_inv, mul_comm]
      _ ≤ δS / ‖quotientChildVector a d‖ :=
        div_le_div_of_nonneg_right hraw (norm_nonneg _)
      _ ≤ δS / (γ - δP) := div_le_div_of_nonneg_left hδS hden hlower
  exact ⟨hsource_ne, htarget_ne, hlower, hsunit, htunit,
    unit_directions_bounds_of_line_residual _ _ hsunit htunit _ hnormalized⟩

/-- Sparse decoding stability separates each child column from a distinct
parent line. This is proved by canceling the child's parent projection with
a code supported on the two columns; it requires only order `2K`, `K≥1`. -/
theorem SparseLowerStable.quotient_column_norm_lower_bound {n M K : ℕ}
    {B : Matrix (Fin n) (Fin M) ℝ} {γ : ℝ}
    (hstable : SparseLowerStable B γ (2 * K)) (hγ : 0 ≤ γ) (hK : 0 < K)
    (i j : Fin M) (hij : i ≠ j) :
    γ ≤ ‖quotientChildVector (representationToEuclidean n (B.col i))
      (representationToEuclidean n (B.col j))‖ := by
  classical
  let W : Submodule ℝ (EuclideanRepresentation n) :=
    ℝ ∙ representationToEuclidean n (B.col i)
  obtain ⟨t, ht⟩ := Submodule.mem_span_singleton.mp
    (W.starProjection_apply_mem (representationToEuclidean n (B.col j)))
  let v : FeatureVector M := Pi.single j 1
  let w : FeatureVector M := v - t • (Pi.single i 1 : FeatureVector M)
  have hwmem : w ∈ coordinateSpan ({i, j} : Finset (Fin M)) := by
    exact (coordinateSpan {i, j}).sub_mem
      (canonicalVector_mem_coordinateSpan {i, j} (by simp))
      ((coordinateSpan {i, j}).smul_mem t
        (canonicalVector_mem_coordinateSpan {i, j} (by simp)))
  have hwcard : (nonzeroSupport w).card ≤ 2 * K := by
    have hle := Finset.card_le_card (nonzeroSupport_subset_of_mem_coordinateSpan hwmem)
    have hpair : ({i, j} : Finset (Fin M)).card = 2 := by simp [hij]
    rw [hpair] at hle
    omega
  have hvi : v i = 0 := by simp only [v, Pi.single_eq_of_ne hij]
  have hnorm := euclidean_norm_le_sub_single_of_zero v i t hvi
  have hvnorm : ‖representationToEuclidean M v‖ = 1 := norm_coefficientBasisVector j
  rw [hvnorm] at hnorm
  have hbound := (mul_le_mul_of_nonneg_left hnorm hγ).trans (hstable w hwcard)
  have hsyn : representationToEuclidean n (B.mulVec w) =
      quotientChildVector (representationToEuclidean n (B.col i))
        (representationToEuclidean n (B.col j)) := by
    rw [quotientChildVector, Submodule.starProjection_orthogonal_val, ← ht]
    simp only [w, v, Matrix.mulVec_sub, Matrix.mulVec_smul, Matrix.mulVec_single_one,
      map_sub, map_smul]
  simpa only [mul_one, hsyn] using hbound

/-- A two-column support is the actual span of its parent and child
vectors in the Euclidean representation. -/
theorem euclideanColumnSpan_pair {n M : ℕ}
    (B : Matrix (Fin n) (Fin M) ℝ) (i j : Fin M) :
    euclideanColumnSpan B {i, j} = Submodule.span ℝ
      ({representationToEuclidean n (B.col i), representationToEuclidean n (B.col j)} :
        Set (EuclideanRepresentation n)) := by
  classical
  have hcolumns : Set.range (selectedColumns B {i, j}) = {B.col i, B.col j} := by
    ext x
    constructor
    · rintro ⟨⟨l, hl⟩, rfl⟩
      rcases Finset.mem_insert.mp hl with hli | hlj
      · subst l
        exact Set.mem_insert _ _
      · have hlj' : l = j := Finset.mem_singleton.mp hlj
        subst l
        exact Set.mem_insert_of_mem _ (Set.mem_singleton _)
    · intro hx
      rcases Set.mem_insert_iff.mp hx with hxi | hxj
      · subst x
        exact ⟨⟨i, by simp⟩, rfl⟩
      · have hxj' : x = B.col j := Set.mem_singleton_iff.mp hxj
        subst x
        exact ⟨⟨j, by simp⟩, rfl⟩
  rw [euclideanColumnSpan, columnSpan, hcolumns, Submodule.map_span, Set.image_pair]
  rfl

/-- The normalized quotient-direction guarantee for actual matched
dictionary columns. Both quotient separation bounds are derived from
sparse decoding stability, and the hypotheses concern only actual parent
lines and two-column support projectors. -/
theorem normalized_quotient_column_recovery {n M m K : ℕ}
    (A : Matrix (Fin n) (Fin M) ℝ) (B : Matrix (Fin n) (Fin m) ℝ)
    (hAunit : HasUnitEuclideanColumns A) (hBunit : HasUnitEuclideanColumns B)
    (γ δP δS : ℝ) (hγ : 0 < γ) (hK : 0 < K) (hsmall : δP < γ)
    (hAstable : SparseLowerStable A γ (2 * K)) (hBstable : SparseLowerStable B γ (2 * K))
    (i j : Fin M) (p q : Fin m) (hij : i ≠ j) (hpq : p ≠ q)
    (hparent : ‖(euclideanColumnSpan A {i}).starProjection -
      (euclideanColumnSpan B {p}).starProjection‖ ≤ δP)
    (hplane : ‖(euclideanColumnSpan A {i, j}).starProjection -
      (euclideanColumnSpan B {p, q}).starProjection‖ ≤ δS) :
    let a := representationToEuclidean n (A.col i)
    let c := representationToEuclidean n (A.col j)
    let d := representationToEuclidean n (B.col q)
    quotientChildVector a c ≠ 0 ∧ quotientChildVector a d ≠ 0 ∧
      γ - δP ≤ ‖quotientChildVector a d‖ ∧
      ‖normalizedQuotientChild a c‖ = 1 ∧ ‖normalizedQuotientChild a d‖ = 1 ∧
      1 - (δS / (γ - δP)) ^ 2 ≤
        |inner ℝ (normalizedQuotientChild a c) (normalizedQuotientChild a d)| ∧
      (‖normalizedQuotientChild a c - normalizedQuotientChild a d‖ ≤ 2 * (δS / (γ - δP)) ∨
        ‖normalizedQuotientChild a c + normalizedQuotientChild a d‖ ≤ 2 * (δS / (γ - δP))) := by
  rw [euclideanColumnSpan_singleton, euclideanColumnSpan_singleton] at hparent
  rw [euclideanColumnSpan_pair, euclideanColumnSpan_pair] at hplane
  exact normalized_quotient_child_recovery _ _ _ _
    ⟨hAunit i, hAunit j, hBunit p, hBunit q⟩ γ δP δS hγ hsmall
    (hAstable.quotient_column_norm_lower_bound hγ.le hK i j hij)
    (hBstable.quotient_column_norm_lower_bound hγ.le hK p q hpq) hparent hplane

end PKG26AtomicFeatures
