import PKG26AtomicFeatures.GenericDimension
import Mathlib.Analysis.Calculus.ContDiff.WithLp

/-!
# Generic dimension on a product of unit spheres

The paper samples each source atom from a unit sphere, so ambient Lebesgue
nullity is not by itself enough: the whole product of spheres is Lebesgue null.
This module instead uses projective charts for both the alternative atoms and
the coefficient vectors.  A chart has `M' * n + M * t` parameters for
representations with `t + 1` terms, while the product of `M` unit `n`-spheres
has Hausdorff dimension `M * n`.

The surface measure below is the Hausdorff measure on the product-sphere
subtype with the metric induced by the Euclidean norm on all coordinates.
-/

open scoped BigOperators Topology
open MeasureTheory Set

namespace PKG26AtomicFeatures

abbrev SphericalSourceSpace (n M : ℕ) :=
  EuclideanSpace ℝ (Fin M × Fin (n + 1))

/-- The `i`th atom of a flattened Euclidean source family. -/
def sphericalSourceAtom {n M : ℕ} (source : SphericalSourceSpace n M)
    (i : Fin M) : EuclideanSpace ℝ (Fin (n + 1)) :=
  WithLp.toLp 2 fun r => source (i, r)

/-- The product of `M` unit spheres in `ℝ^(n+1)`, with its metric induced from
the Euclidean norm on the full flattened coordinate family. -/
def productUnitSphereSet (n M : ℕ) : Set (SphericalSourceSpace n M) :=
  {source | ∀ i, ‖sphericalSourceAtom source i‖ = 1}

abbrev ProductUnitSphere (n M : ℕ) := productUnitSphereSet n M

/-- Intrinsic `M*n`-dimensional Hausdorff surface measure on the product of
unit `n`-spheres. -/
noncomputable abbrev productUnitSphereSurfaceMeasure (n M : ℕ) :
    Measure (ProductUnitSphere n M) := μH[M * n]

/-- Forget the unit-norm proofs and view a spherical source family in the
coordinate convention used by `STermRepresentable`. -/
def ProductUnitSphere.atomFamily {n M : ℕ} (source : ProductUnitSphere n M) :
    (Fin M × Fin (n + 1)) → ℝ :=
  fun ir => source.1 ir

/-- Reassemble a spherical source family as the matrix whose columns are its
unit atoms. -/
def ProductUnitSphere.matrix {n M : ℕ} (source : ProductUnitSphere n M) :
    Matrix (Fin (n + 1)) (Fin M) ℝ :=
  fun r i => source.1 (i, r)

@[simp] theorem ProductUnitSphere.matrixAtomFamily_matrix {n M : ℕ}
    (source : ProductUnitSphere n M) :
    matrixAtomFamily (ProductUnitSphere.matrix source) =
      ProductUnitSphere.atomFamily source := rfl

/-- One fewer free coefficient per source atom after choosing a nonzero
coefficient as a projective pivot. -/
abbrev SphericalCoefficientParameters (M t : ℕ) :=
  GenericCoefficientParameters M t

abbrev SphericalIncidenceParameters (n M M' t : ℕ) :=
  GenericAtomParameters n M' × SphericalCoefficientParameters M t

/-- The two orientations of a real projective coefficient chart. -/
def coefficientChartSign (orientation : Bool) : ℝ :=
  if orientation then -1 else 1

theorem exists_coefficientChartSign (x : ℝ) (hx : x ≠ 0) :
    ∃ orientation : Bool, x = coefficientChartSign orientation * |x| := by
  by_cases hpos : 0 < x
  · refine ⟨false, ?_⟩
    simp [coefficientChartSign, abs_of_pos hpos]
  · have hneg : x < 0 := lt_of_le_of_ne (le_of_not_gt hpos) hx
    refine ⟨true, ?_⟩
    simp [coefficientChartSign, abs_of_neg hneg]

/-- A coefficient chart with one coordinate fixed to `+1` or `-1`. -/
def chartCoefficient {M t : ℕ} (orientation : Fin M → Bool)
    (pivot : Fin M → Fin (t + 1))
    (coefficients : SphericalCoefficientParameters M t)
    (i : Fin M) (k : Fin (t + 1)) : ℝ :=
  if h : k = pivot i then coefficientChartSign (orientation i) else
    coefficients i ((finSuccAboveEquiv (pivot i)).symm ⟨k, h⟩)

/-- The unnormalized source atom generated in a fixed support and projective
chart. -/
def sphericalRawIncidenceAtom {n M M' t : ℕ}
    (atomPivot : Fin M' → Fin (n + 1))
    (orientation : Fin M → Bool)
    (coefficientPivot : Fin M → Fin (t + 1))
    (indices : Fin M → Fin (t + 1) → Fin M')
    (parameters : SphericalIncidenceParameters n M M' t)
    (i : Fin M) : EuclideanSpace ℝ (Fin (n + 1)) :=
  WithLp.toLp 2 fun r =>
    ∑ k : Fin (t + 1),
      chartCoefficient orientation coefficientPivot parameters.2 i k *
        chartAtom atomPivot parameters.1 (indices i k) r

/-- The open chart locus on which every generated source atom is nonzero and
hence admits smooth radial normalization. -/
def sphericalIncidenceDomain {n M M' t : ℕ}
    (atomPivot : Fin M' → Fin (n + 1))
    (orientation : Fin M → Bool)
    (coefficientPivot : Fin M → Fin (t + 1))
    (indices : Fin M → Fin (t + 1) → Fin M') :
    Set (SphericalIncidenceParameters n M M' t) :=
  {parameters | ∀ i,
    sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
      parameters i ≠ 0}

/-- Radially normalize every atom generated by a fixed projective chart. -/
noncomputable def sphericalIncidenceParamMap {n M M' t : ℕ}
    (atomPivot : Fin M' → Fin (n + 1))
    (orientation : Fin M → Bool)
    (coefficientPivot : Fin M → Fin (t + 1))
    (indices : Fin M → Fin (t + 1) → Fin M') :
    SphericalIncidenceParameters n M M' t → SphericalSourceSpace n M :=
  fun parameters => WithLp.toLp 2 fun ir =>
    sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
        parameters ir.1 ir.2 /
      ‖sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
        parameters ir.1‖

theorem sphericalRawIncidenceAtom_contDiff {n M M' t : ℕ}
    (atomPivot : Fin M' → Fin (n + 1))
    (orientation : Fin M → Bool)
    (coefficientPivot : Fin M → Fin (t + 1))
    (indices : Fin M → Fin (t + 1) → Fin M') (i : Fin M) :
    ContDiff ℝ 1
      (fun parameters : SphericalIncidenceParameters n M M' t =>
        sphericalRawIncidenceAtom atomPivot orientation coefficientPivot
          indices parameters i) := by
  rw [contDiff_piLp]
  intro r
  simp only [sphericalRawIncidenceAtom]
  apply ContDiff.sum
  intro k _hk
  have hcoeff : ContDiff ℝ 1
      (fun parameters : SphericalIncidenceParameters n M M' t =>
        chartCoefficient orientation coefficientPivot parameters.2 i k) := by
    by_cases hk : k = coefficientPivot i
    · simp only [chartCoefficient, dif_pos hk]
      exact contDiff_const
    · simp [chartCoefficient, hk]
      fun_prop
  have hatom : ContDiff ℝ 1
      (fun parameters : SphericalIncidenceParameters n M M' t =>
        chartAtom atomPivot parameters.1 (indices i k) r) := by
    by_cases hr : r = atomPivot (indices i k)
    · simp only [chartAtom, dif_pos hr]
      exact contDiff_const
    · simp [chartAtom, hr]
      fun_prop
  exact hcoeff.mul hatom

theorem sphericalIncidenceParamMap_contDiffAt {n M M' t : ℕ}
    (atomPivot : Fin M' → Fin (n + 1))
    (orientation : Fin M → Bool)
    (coefficientPivot : Fin M → Fin (t + 1))
    (indices : Fin M → Fin (t + 1) → Fin M')
    {parameters : SphericalIncidenceParameters n M M' t}
    (hparameters : parameters ∈ sphericalIncidenceDomain atomPivot orientation
      coefficientPivot indices) :
    ContDiffAt ℝ 1
      (sphericalIncidenceParamMap atomPivot orientation coefficientPivot indices)
      parameters := by
  rw [contDiffAt_piLp]
  rintro ⟨i, r⟩
  have hraw := sphericalRawIncidenceAtom_contDiff atomPivot orientation
    coefficientPivot indices i
  have hrawCoordinate : ContDiff ℝ 1
      (fun parameters : SphericalIncidenceParameters n M M' t =>
        sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
          parameters i r) := by
    rw [contDiff_piLp] at hraw
    exact hraw r
  exact hrawCoordinate.contDiffAt.div
    (hraw.contDiffAt.norm ℝ (hparameters i))
    (norm_ne_zero_iff.mpr (hparameters i))

theorem finrank_sphericalIncidenceParameters (n M M' t : ℕ) :
    Module.finrank ℝ (SphericalIncidenceParameters n M M' t) =
      M' * n + M * t := by
  simp [SphericalIncidenceParameters, SphericalCoefficientParameters,
    GenericAtomParameters, GenericCoefficientParameters,
    Module.finrank_pi_fintype]

/-- Each fixed support/projective chart has zero `M*n`-dimensional Hausdorff
measure when its parameter dimension is strictly smaller than `M*n`. -/
theorem sphericalIncidenceParamMap_image_hausdorffMeasure_eq_zero
    {n M M' t : ℕ}
    (atomPivot : Fin M' → Fin (n + 1))
    (orientation : Fin M → Bool)
    (coefficientPivot : Fin M → Fin (t + 1))
    (indices : Fin M → Fin (t + 1) → Fin M')
    (hdim : M' * n + M * t < M * n) :
    μH[M * n]
      (sphericalIncidenceParamMap atomPivot orientation coefficientPivot indices ''
        sphericalIncidenceDomain atomPivot orientation coefficientPivot indices) = 0 := by
  let domain := sphericalIncidenceDomain atomPivot orientation coefficientPivot indices
  let map := sphericalIncidenceParamMap atomPivot orientation coefficientPivot indices
  have hlocal : ∀ parameters ∈ domain,
      ∃ C : NNReal, ∃ u ∈ 𝓝[domain] parameters, LipschitzOnWith C map u := by
    intro parameters hparameters
    obtain ⟨C, u, hu, hCu⟩ :=
      (sphericalIncidenceParamMap_contDiffAt atomPivot orientation coefficientPivot
        indices hparameters).exists_lipschitzOnWith
    exact ⟨C, u, mem_nhdsWithin_of_mem_nhds hu, hCu⟩
  have himage : dimH (map '' domain) ≤
      Module.finrank ℝ (SphericalIncidenceParameters n M M' t) := by
    calc
      dimH (map '' domain) ≤ dimH domain :=
        dimH_image_le_of_locally_lipschitzOn hlocal
      _ ≤ dimH (Set.univ : Set (SphericalIncidenceParameters n M M' t)) :=
        dimH_mono (Set.subset_univ domain)
      _ = Module.finrank ℝ (SphericalIncidenceParameters n M M' t) :=
        Real.dimH_univ_eq_finrank _
  have hfinrank : Module.finrank ℝ
      (SphericalIncidenceParameters n M M' t) < M * n := by
    rw [finrank_sphericalIncidenceParameters]
    exact hdim
  have hdimH : dimH (map '' domain) < (M * n : ENNReal) :=
    himage.trans_lt (by exact_mod_cast hfinrank)
  exact hausdorffMeasure_of_dimH_lt (d := (M * n : NNReal)) hdimH

/-- The finite union of all projective charts for `(t+1)`-term
representations. -/
def sphericalIncidenceBadSet (n M M' t : ℕ) : Set (SphericalSourceSpace n M) :=
  ⋃ atomPivot : Fin M' → Fin (n + 1),
    ⋃ orientation : Fin M → Bool,
      ⋃ coefficientPivot : Fin M → Fin (t + 1),
        ⋃ indices : Fin M → Fin (t + 1) → Fin M',
          sphericalIncidenceParamMap atomPivot orientation coefficientPivot indices ''
            sphericalIncidenceDomain atomPivot orientation coefficientPivot indices

theorem sphericalIncidenceBadSet_hausdorffMeasure_eq_zero
    {n M M' t : ℕ} (hdim : M' * n + M * t < M * n) :
    μH[M * n] (sphericalIncidenceBadSet n M M' t) = 0 := by
  rw [sphericalIncidenceBadSet]
  apply measure_iUnion_null
  intro atomPivot
  apply measure_iUnion_null
  intro orientation
  apply measure_iUnion_null
  intro coefficientPivot
  apply measure_iUnion_null
  intro indices
  exact sphericalIncidenceParamMap_image_hausdorffMeasure_eq_zero
    atomPivot orientation coefficientPivot indices hdim

/-- A unit source atom cannot have a representation with no coefficient
slots. -/
theorem ProductUnitSphere.not_sTermRepresentable_zero
    {n M M' : ℕ} (source : ProductUnitSphere n M) (hM : 0 < M) :
    ¬ STermRepresentable M' 0 (ProductUnitSphere.atomFamily source) := by
  rintro ⟨alternative, indices, coefficients, hsource⟩
  let i : Fin M := ⟨0, hM⟩
  have hrow : sphericalSourceAtom source.1 i = 0 := by
    ext r
    have hcoordinate := congrFun hsource (i, r)
    simp [ProductUnitSphere.atomFamily, atomFamilyFromTerms,
      sphericalSourceAtom] at hcoordinate ⊢
    exact hcoordinate
  have hnorm := source.2 i
  rw [hrow, norm_zero] at hnorm
  norm_num at hnorm

/-- Every unit source family with a `(t+1)`-term representation belongs to a
fixed finite union of projective incidence charts. -/
theorem ProductUnitSphere.val_mem_sphericalIncidenceBadSet_of_sTermRepresentable
    {n M M' t : ℕ} (source : ProductUnitSphere n M)
    (hrepresentable : STermRepresentable M' (t + 1)
      (ProductUnitSphere.atomFamily source)) :
    source.1 ∈ sphericalIncidenceBadSet n M M' t := by
  classical
  obtain ⟨alternative, indices, coefficients, hsource⟩ := hrepresentable
  have hatomPivotExists : ∀ j : Fin M', ∃ r : Fin (n + 1),
      alternative.col j = 0 ∨ alternative r j ≠ 0 := by
    intro j
    by_cases hzero : alternative.col j = 0
    · exact ⟨0, Or.inl hzero⟩
    · have hexists : ∃ r, alternative r j ≠ 0 := by
        by_contra hnot
        push Not at hnot
        apply hzero
        funext r
        exact hnot r
      obtain ⟨r, hr⟩ := hexists
      exact ⟨r, Or.inr hr⟩
  choose atomPivot hatomPivot using hatomPivotExists
  let atoms : GenericAtomParameters n M' := fun j u =>
    if alternative.col j = 0 then 0 else
      alternative ((finSuccAboveEquiv (atomPivot j)) u).1 j /
        alternative (atomPivot j) j
  let scaledCoefficients : GenericCoefficientParameters M (t + 1) :=
    fun i k =>
      if alternative.col (indices i k) = 0 then 0 else
        coefficients i k *
          alternative (atomPivot (indices i k)) (indices i k)
  have hscaled : ∀ i r, source.1 (i, r) =
      ∑ k : Fin (t + 1), scaledCoefficients i k *
        chartAtom atomPivot atoms (indices i k) r := by
    intro i r
    have hcoordinate := congrFun hsource (i, r)
    simp only [ProductUnitSphere.atomFamily, atomFamilyFromTerms] at hcoordinate
    rw [hcoordinate]
    apply Finset.sum_congr rfl
    intro k _hk
    by_cases hzero : alternative.col (indices i k) = 0
    · have hentry : alternative r (indices i k) = 0 :=
        congrFun hzero r
      simp [scaledCoefficients, hzero, hentry]
    · have hpivotNe : alternative (atomPivot (indices i k))
          (indices i k) ≠ 0 :=
        (hatomPivot (indices i k)).resolve_left hzero
      by_cases hr : r = atomPivot (indices i k)
      · simp [scaledCoefficients, chartAtom, hzero, hr]
      · simp [scaledCoefficients, chartAtom, atoms, hzero, hr]
        field_simp
  have hcoefficientPivotExists : ∀ i : Fin M,
      ∃ k : Fin (t + 1), scaledCoefficients i k ≠ 0 := by
    intro i
    by_contra hnot
    push Not at hnot
    have hrow : sphericalSourceAtom source.1 i = 0 := by
      ext r
      simp only [sphericalSourceAtom]
      rw [hscaled i r]
      simp [hnot]
    have hnorm := source.2 i
    rw [hrow, norm_zero] at hnorm
    norm_num at hnorm
  choose coefficientPivot hcoefficientPivot using hcoefficientPivotExists
  have horientationExists : ∀ i : Fin M, ∃ orientation : Bool,
      scaledCoefficients i (coefficientPivot i) =
        coefficientChartSign orientation *
          |scaledCoefficients i (coefficientPivot i)| := by
    intro i
    exact exists_coefficientChartSign _ (hcoefficientPivot i)
  choose orientation horientation using horientationExists
  let chartCoefficients : SphericalCoefficientParameters M t := fun i u =>
    scaledCoefficients i ((finSuccAboveEquiv (coefficientPivot i)) u).1 /
      |scaledCoefficients i (coefficientPivot i)|
  let parameters : SphericalIncidenceParameters n M M' t :=
    (atoms, chartCoefficients)
  have habsPivotNe (i : Fin M) :
      |scaledCoefficients i (coefficientPivot i)| ≠ 0 :=
    abs_ne_zero.mpr (hcoefficientPivot i)
  have hchartCoefficient (i : Fin M) (k : Fin (t + 1)) :
      chartCoefficient orientation coefficientPivot chartCoefficients i k =
        scaledCoefficients i k /
          |scaledCoefficients i (coefficientPivot i)| := by
    by_cases hk : k = coefficientPivot i
    · subst k
      simp only [chartCoefficient]
      exact (eq_div_iff (habsPivotNe i)).2 (horientation i).symm
    · simp only [chartCoefficient, dif_neg hk, chartCoefficients]
      congr 2
      exact congrArg Subtype.val
        ((finSuccAboveEquiv (coefficientPivot i)).apply_symm_apply ⟨k, hk⟩)
  have hrawCoordinate (i : Fin M) (r : Fin (n + 1)) :
      sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
          parameters i r =
        source.1 (i, r) /
          |scaledCoefficients i (coefficientPivot i)| := by
    simp only [sphericalRawIncidenceAtom, parameters]
    calc
      (∑ k : Fin (t + 1),
          chartCoefficient orientation coefficientPivot chartCoefficients i k *
            chartAtom atomPivot atoms (indices i k) r) =
          ∑ k : Fin (t + 1),
            (scaledCoefficients i k /
              |scaledCoefficients i (coefficientPivot i)|) *
                chartAtom atomPivot atoms (indices i k) r := by
        apply Finset.sum_congr rfl
        intro k _hk
        rw [hchartCoefficient]
      _ = (∑ k : Fin (t + 1), scaledCoefficients i k *
          chartAtom atomPivot atoms (indices i k) r) /
            |scaledCoefficients i (coefficientPivot i)| := by
        rw [Finset.sum_div]
        apply Finset.sum_congr rfl
        intro k _hk
        ring
      _ = source.1 (i, r) /
          |scaledCoefficients i (coefficientPivot i)| := by
        rw [hscaled]
  have hrawVector (i : Fin M) :
      sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
          parameters i =
        |scaledCoefficients i (coefficientPivot i)|⁻¹ •
          sphericalSourceAtom source.1 i := by
    ext r
    rw [hrawCoordinate]
    simp [sphericalSourceAtom, div_eq_inv_mul]
  have hsourceAtomNe (i : Fin M) : sphericalSourceAtom source.1 i ≠ 0 := by
    apply norm_ne_zero_iff.mp
    rw [source.2 i]
    norm_num
  have hparameters : parameters ∈ sphericalIncidenceDomain atomPivot orientation
      coefficientPivot indices := by
    intro i
    rw [hrawVector]
    exact smul_ne_zero (inv_ne_zero (habsPivotNe i)) (hsourceAtomNe i)
  have hmap : sphericalIncidenceParamMap atomPivot orientation coefficientPivot
      indices parameters = source.1 := by
    ext ir
    simp only [sphericalIncidenceParamMap]
    rw [hrawCoordinate]
    have habsPos : 0 < |scaledCoefficients ir.1 (coefficientPivot ir.1)| :=
      abs_pos.mpr (hcoefficientPivot ir.1)
    have hrawNorm :
        ‖sphericalRawIncidenceAtom atomPivot orientation coefficientPivot indices
          parameters ir.1‖ =
          |scaledCoefficients ir.1 (coefficientPivot ir.1)|⁻¹ := by
      rw [hrawVector, norm_smul, source.2]
      simp [Real.norm_eq_abs]
    rw [hrawNorm]
    field_simp
  rw [sphericalIncidenceBadSet]
  apply Set.mem_iUnion.mpr
  refine ⟨atomPivot, ?_⟩
  apply Set.mem_iUnion.mpr
  refine ⟨orientation, ?_⟩
  apply Set.mem_iUnion.mpr
  refine ⟨coefficientPivot, ?_⟩
  apply Set.mem_iUnion.mpr
  refine ⟨indices, ?_⟩
  exact ⟨parameters, hparameters, hmap⟩

/-- For a fixed alternative width and fixed positive sparsity, the
representable unit source families form a surface-null set whenever the
paper's projective dimension inequality fails. -/
theorem sTermRepresentable_succ_productUnitSphereSurfaceMeasure_eq_zero
    {n M M' t : ℕ} (hdim : M' * n + M * t < M * n) :
    (productUnitSphereSurfaceMeasure n M)
      {source | STermRepresentable M' (t + 1)
        (ProductUnitSphere.atomFamily source)} = 0 := by
  let bad : Set (ProductUnitSphere n M) :=
    {source | STermRepresentable M' (t + 1)
      (ProductUnitSphere.atomFamily source)}
  have himage : μH[M * n] (((↑) : ProductUnitSphere n M →
      SphericalSourceSpace n M) '' bad) = 0 := by
    apply measure_mono_null
    · rintro _source ⟨source, hsource, rfl⟩
      exact ProductUnitSphere.val_mem_sphericalIncidenceBadSet_of_sTermRepresentable
        source hsource
    · exact sphericalIncidenceBadSet_hausdorffMeasure_eq_zero hdim
  rw [isometry_subtype_coe.hausdorffMeasure_image
    (Or.inl (by positivity : (0 : ℝ) ≤ M * n))] at himage
  exact himage

/-- Projective-dimension genericity on the product sphere.  The coefficient
count is `s-1` because nonzero source atoms allow radial normalization. -/
def SphericalProjectiveDimensionGeneric {n M : ℕ}
    (source : ProductUnitSphere n M) : Prop :=
  ∀ M' s, STermRepresentable M' s (ProductUnitSphere.atomFamily source) →
    M * n ≤ M' * n + M * (s - 1)

/-- Almost every family of unit source atoms satisfies the projective
dimension bound simultaneously for every alternative width and every finite
term budget. -/
theorem ae_sphericalProjectiveDimensionGeneric (n M : ℕ) :
    ∀ᵐ source ∂productUnitSphereSurfaceMeasure n M,
      SphericalProjectiveDimensionGeneric source := by
  simp only [SphericalProjectiveDimensionGeneric]
  rw [ae_all_iff]
  intro M'
  rw [ae_all_iff]
  intro s
  by_cases hdim : M' * n + M * (s - 1) < M * n
  · cases s with
    | zero =>
        have hM : 0 < M := by
          by_contra hM
          have hMzero : M = 0 := Nat.eq_zero_of_not_pos hM
          subst M
          simp at hdim
        exact Filter.Eventually.of_forall fun source hrepresentable =>
          False.elim
            (ProductUnitSphere.not_sTermRepresentable_zero source hM hrepresentable)
    | succ t =>
        filter_upwards [measure_eq_zero_iff_ae_notMem.mp
          (sTermRepresentable_succ_productUnitSphereSurfaceMeasure_eq_zero
            (by simpa using hdim))] with source hsource
        intro hrepresentable
        exact False.elim (hsource hrepresentable)
  · exact Filter.Eventually.of_forall fun _source _hrepresentable =>
      Nat.le_of_not_gt hdim

/-- The same conclusion holds under any joint law on the product sphere that
is absolutely continuous with respect to its Hausdorff surface measure. -/
theorem ae_sphericalProjectiveDimensionGeneric_of_absolutelyContinuous
    {n M : ℕ} (distribution : Measure (ProductUnitSphere n M))
    (hdistribution : distribution ≪ productUnitSphereSurfaceMeasure n M) :
    ∀ᵐ source ∂distribution, SphericalProjectiveDimensionGeneric source := by
  exact hdistribution.ae_le (ae_sphericalProjectiveDimensionGeneric n M)

/-- Sparse representations of all source columns instantiate the spherical
genericity predicate directly. -/
theorem SphericalProjectiveDimensionGeneric.dimension_bound_of_sparse_atom_factorization
    {n M M' s : ℕ} {source : ProductUnitSphere n M}
    (hgeneric : SphericalProjectiveDimensionGeneric source)
    (hs : s ≤ M')
    (alternative : Matrix (Fin (n + 1)) (Fin M') ℝ)
    (code : Fin M → FeatureVector M')
    (hsparse : ∀ i, (nonzeroSupport (code i)).card ≤ s)
    (hfactors : ∀ i, (ProductUnitSphere.matrix source).col i =
      alternative.mulVec (code i)) :
    M * n ≤ M' * n + M * (s - 1) := by
  apply hgeneric M' s
  rw [← ProductUnitSphere.matrixAtomFamily_matrix source]
  exact sTermRepresentable_of_sparse_atom_factorization hs
    (ProductUnitSphere.matrix source) alternative code hsparse hfactors

/-- Integer-sharp form of the paper's displayed lower bound.  In paper
notation `n = d-1`, so the numerator is
`M + (M-M')*(d-1)`. -/
theorem ceil_spherical_sparsity_lower_bound_of_sTermRepresentable
    {n M M' s : ℕ} (hM : 0 < M) (hwidth : M' ≤ M)
    {source : ProductUnitSphere n M}
    (hgeneric : SphericalProjectiveDimensionGeneric source)
    (hrepresentable : STermRepresentable M' s
      (ProductUnitSphere.atomFamily source)) :
    (M + (M - M') * n) ⌈/⌉ M ≤ s := by
  rw [ceilDiv_le_iff_le_mul hM]
  have hdim := hgeneric M' s hrepresentable
  have hsplit : M * n = M' * n + (M - M') * n := by
    conv_lhs => rw [show M = M' + (M - M') by omega]
    exact Nat.add_mul M' (M - M') n
  rw [hsplit] at hdim
  by_cases hs : s = 0
  · subst s
    exact False.elim
      (ProductUnitSphere.not_sTermRepresentable_zero source hM hrepresentable)
  · have hspos : 0 < s := Nat.pos_of_ne_zero hs
    have hsSplit : M * s = M + M * (s - 1) := by
      calc
        M * s = M * (1 + (s - 1)) := by rw [Nat.add_sub_of_le hspos]
        _ = M + M * (s - 1) := by simp [Nat.mul_add]
    have hcoeff : (M - M') * n ≤ M * (s - 1) := by
      omega
    rw [hsSplit]
    omega

/-! ## Nonvacuity of product-sphere surface measure -/

abbrev ProductUnitSphereChartParameters (n M : ℕ) :=
  EuclideanSpace ℝ (Fin M × Fin n)

abbrev ProductUnitSphereChartDomain (n M : ℕ) :=
  Metric.closedBall (0 : ProductUnitSphereChartParameters n M) (1 / 2 : ℝ)

private theorem productUnitSphereChart_row_sq_le
    {n M : ℕ} {x : ProductUnitSphereChartParameters n M}
    (hx : x ∈ Metric.closedBall 0 (1 / 2 : ℝ)) (i : Fin M) :
    ∑ k : Fin n, x (i, k) ^ 2 ≤ 1 := by
  have hrow : (∑ k : Fin n, x (i, k) ^ 2) ≤
      ∑ ir : Fin M × Fin n, x ir ^ 2 := by
    rw [Fintype.sum_prod_type]
    simpa only [Finset.sum_singleton] using
      (Finset.sum_le_univ_sum_of_nonneg
        (s := {i}) (f := fun j : Fin M => ∑ k : Fin n, x (j, k) ^ 2)
        (fun _ => Finset.sum_nonneg fun _ _ => sq_nonneg _))
  have hxnorm : ‖x‖ ≤ (1 / 2 : ℝ) := by
    simpa [Metric.mem_closedBall, dist_zero_right] using hx
  rw [← EuclideanSpace.real_norm_sq_eq] at hrow
  nlinarith [norm_nonneg x]

/-- Upper-hemisphere coordinates for a bounded Euclidean chart. -/
noncomputable def productUnitSphereChartAmbient {n M : ℕ}
    (x : ProductUnitSphereChartParameters n M) : SphericalSourceSpace n M :=
  WithLp.toLp 2 fun ir =>
    Fin.cases (Real.sqrt (1 - ∑ k : Fin n, x (ir.1, k) ^ 2))
      (fun k => x (ir.1, k)) ir.2

private theorem productUnitSphereChartAmbient_mem
    {n M : ℕ} {x : ProductUnitSphereChartParameters n M}
    (hx : x ∈ Metric.closedBall 0 (1 / 2 : ℝ)) :
    productUnitSphereChartAmbient x ∈ productUnitSphereSet n M := by
  intro i
  have hrow := productUnitSphereChart_row_sq_le hx i
  have hsqrt : Real.sqrt (1 - ∑ k : Fin n, x (i, k) ^ 2) ^ 2 =
      1 - ∑ k : Fin n, x (i, k) ^ 2 :=
    Real.sq_sqrt (sub_nonneg.mpr hrow)
  have hnormSq :
      ‖sphericalSourceAtom (productUnitSphereChartAmbient x) i‖ ^ 2 = 1 := by
    rw [EuclideanSpace.real_norm_sq_eq, Fin.sum_univ_succ]
    simp only [sphericalSourceAtom, productUnitSphereChartAmbient,
      Fin.cases_zero, Fin.cases_succ]
    rw [hsqrt]
    ring
  nlinarith [norm_nonneg
    (sphericalSourceAtom (productUnitSphereChartAmbient x) i)]

/-- A bounded Euclidean upper-hemisphere chart into the product sphere. -/
noncomputable def productUnitSphereChart {n M : ℕ}
    (x : ProductUnitSphereChartDomain n M) : ProductUnitSphere n M :=
  ⟨productUnitSphereChartAmbient x.1,
    productUnitSphereChartAmbient_mem x.2⟩

/-- Drop the first coordinate of every atom. -/
def productUnitSphereLowerCoordinates {n M : ℕ}
    (source : SphericalSourceSpace n M) :
    ProductUnitSphereChartParameters n M :=
  WithLp.toLp 2 fun ik => source (ik.1, ik.2.succ)

theorem productUnitSphereLowerCoordinates_lipschitzWith
    (n M : ℕ) :
    LipschitzWith 1 (@productUnitSphereLowerCoordinates n M) := by
  apply LipschitzWith.mk_one
  intro source₁ source₂
  have hsq :
      dist (productUnitSphereLowerCoordinates source₁)
          (productUnitSphereLowerCoordinates source₂) ^ 2 ≤
        dist source₁ source₂ ^ 2 := by
    rw [EuclideanSpace.dist_sq_eq, EuclideanSpace.dist_sq_eq,
      Fintype.sum_prod_type, Fintype.sum_prod_type]
    apply Finset.sum_le_sum
    intro i _hi
    rw [Fin.sum_univ_succ]
    simp only [productUnitSphereLowerCoordinates]
    exact le_add_of_nonneg_left (sq_nonneg _)
  have hleft : 0 ≤ dist (productUnitSphereLowerCoordinates source₁)
      (productUnitSphereLowerCoordinates source₂) := dist_nonneg
  have hright : 0 ≤ dist source₁ source₂ := dist_nonneg
  nlinarith

@[simp] theorem productUnitSphereLowerCoordinates_chart
    {n M : ℕ} (x : ProductUnitSphereChartDomain n M) :
    productUnitSphereLowerCoordinates (productUnitSphereChart x).1 = x.1 := by
  ext ik
  rfl

theorem productUnitSphereChart_antilipschitzWith (n M : ℕ) :
    AntilipschitzWith 1 (@productUnitSphereChart n M) := by
  rw [antilipschitzWith_iff_le_mul_dist]
  intro x y
  simp only [NNReal.coe_one, one_mul]
  have hprojection :=
    (productUnitSphereLowerCoordinates_lipschitzWith n M).dist_le_mul
      (productUnitSphereChart x).1 (productUnitSphereChart y).1
  simpa using hprojection

/-- The intrinsic Hausdorff surface measure on the product sphere is
nonzero, so the almost-everywhere genericity theorem is nonvacuous. -/
theorem productUnitSphereSurfaceMeasure_ne_zero (n M : ℕ) :
    productUnitSphereSurfaceMeasure n M ≠ 0 := by
  let parameterSpace := ProductUnitSphereChartParameters n M
  let domain := ProductUnitSphereChartDomain n M
  have hball : 0 < (μH[M * n] : Measure parameterSpace)
      (Metric.closedBall 0 (1 / 2 : ℝ)) := by
    have hfinrank : Module.finrank ℝ parameterSpace = M * n := by
      simp [parameterSpace, ProductUnitSphereChartParameters]
    simpa [hfinrank] using
      (Metric.measure_closedBall_pos
        (μ := (μH[Module.finrank ℝ parameterSpace] : Measure parameterSpace))
        (0 : parameterSpace) (by norm_num : (0 : ℝ) < 1 / 2))
  have hdomain : 0 < (μH[M * n] : Measure domain) Set.univ := by
    rw [← isometry_subtype_coe.hausdorffMeasure_image
      (Or.inl (by positivity : (0 : ℝ) ≤ M * n))]
    rw [Set.image_univ, Subtype.range_coe]
    exact hball
  have hchart := (productUnitSphereChart_antilipschitzWith n M)
    |>.le_hausdorffMeasure_image
      (by positivity : (0 : ℝ) ≤ M * n) (Set.univ : Set domain)
  have himage : 0 < (μH[M * n] : Measure (ProductUnitSphere n M))
      (productUnitSphereChart '' (Set.univ : Set domain)) := by
    apply hdomain.trans_le
    simpa using hchart
  have huniv : 0 < (productUnitSphereSurfaceMeasure n M) Set.univ :=
    himage.trans_le (measure_mono (Set.subset_univ _))
  intro hzero
  rw [hzero] at huniv
  simp at huniv

end PKG26AtomicFeatures
