import PKG26AtomicFeatures.TwoColumnStability
import Mathlib.Analysis.Normed.Module.Normalize

/-!
# Angular diameter of a cone generated by two unit columns

Nonnegative combinations of two unit vectors cannot make an angle more
obtuse than the generators when their correlation is negative. When the
generator correlation is nonnegative, every pair of combinations has
nonnegative inner product. In particular, a normalized two-column dictionary
with decoding margin one half has cone cosine at least minus three quarters.
-/

namespace PKG26AtomicFeatures

open scoped InnerProductSpace

/-- A lower bound on the correlation of two unit generators bounds every
pair of nonnegative combinations. The allowance `r` is nonnegative; no
angle enclosure of the cone is assumed. Zero combinations are included. -/
theorem inner_nonnegative_two_generator_combinations_ge
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (b₀ b₁ : E) (hb₀ : ‖b₀‖ = 1) (hb₁ : ‖b₁‖ = 1)
    (r : ℝ) (hr : 0 ≤ r) (hcorrelation : -r ≤ inner ℝ b₀ b₁)
    (u₀ u₁ v₀ v₁ : ℝ) (hu₀ : 0 ≤ u₀) (hu₁ : 0 ≤ u₁)
    (hv₀ : 0 ≤ v₀) (hv₁ : 0 ≤ v₁) :
    -r * ‖u₀ • b₀ + u₁ • b₁‖ * ‖v₀ • b₀ + v₁ • b₁‖ ≤
      inner ℝ (u₀ • b₀ + u₁ • b₁) (v₀ • b₀ + v₁ • b₁) := by
  let x := u₀ • b₀ + u₁ • b₁
  let y := v₀ • b₀ + v₁ • b₁
  change -r * ‖x‖ * ‖y‖ ≤ inner ℝ x y
  by_cases hnonneg : 0 ≤ inner ℝ x y
  · exact (mul_nonpos_of_nonpos_of_nonneg
      (mul_nonpos_of_nonpos_of_nonneg (neg_nonpos.mpr hr) (norm_nonneg x))
      (norm_nonneg y)).trans hnonneg
  have hnegative : inner ℝ x y < 0 := lt_of_not_ge hnonneg
  let c := inner ℝ b₀ b₁
  let X := u₀ * v₀ + u₁ * v₁
  let Y := u₀ * v₁ + u₁ * v₀
  let P := u₀ * u₁ * v₀ * v₁
  have hX : 0 ≤ X := by dsimp [X]; positivity
  have hY : 0 ≤ Y := by dsimp [Y]; positivity
  have hP : 0 ≤ P := by dsimp [P]; positivity
  have hinner : inner ℝ x y = X + c * Y := by
    dsimp [x, y, X, Y, c]
    simp only [inner_add_left, inner_add_right, real_inner_smul_left,
      real_inner_smul_right, real_inner_self_eq_norm_sq, hb₀, hb₁,
      real_inner_comm b₁ b₀]
    ring
  have hc : c < 0 := by
    by_contra hn
    have hproduct := mul_nonneg (le_of_not_gt hn) hY
    rw [hinner] at hnegative
    linarith
  have hcabs : |c| ≤ 1 := by
    simpa only [c, hb₀, hb₁, mul_one] using abs_real_inner_le_norm b₀ b₁
  have hcsq : c ^ 2 ≤ 1 := by
    have h := (sq_le_sq₀ (abs_nonneg c) zero_le_one).mpr hcabs
    simpa only [sq_abs, one_pow] using h
  have hnormx : ‖x‖ ^ 2 = u₀ ^ 2 + u₁ ^ 2 + 2 * c * u₀ * u₁ := by
    dsimp [x, c]
    rw [norm_add_sq_real]
    simp only [norm_smul, Real.norm_eq_abs, hb₀, hb₁, mul_one, sq_abs,
      real_inner_smul_left, real_inner_smul_right]
    ring
  have hnormy : ‖y‖ ^ 2 = v₀ ^ 2 + v₁ ^ 2 + 2 * c * v₀ * v₁ := by
    dsimp [y, c]
    rw [norm_add_sq_real]
    simp only [norm_smul, Real.norm_eq_abs, hb₀, hb₁, mul_one, sq_abs,
      real_inner_smul_left, real_inner_smul_right]
    ring
  have hfour : 4 * P ≤ X ^ 2 := by
    dsimp [P, X]
    nlinarith only [sq_nonneg (u₀ * v₀ - u₁ * v₁)]
  have hfourc : 4 * c ^ 2 * P ≤ X ^ 2 := by
    have h := mul_le_mul_of_nonneg_right hcsq (show 0 ≤ 4 * P by positivity)
    nlinarith only [h, hfour]
  have hXI : X * (X + c * Y) ≤ 0 :=
    mul_nonpos_of_nonneg_of_nonpos hX (by rw [← hinner]; exact hnegative.le)
  have hbracket : X ^ 2 + 2 * c * X * Y + 4 * c ^ 2 * P ≤ 0 := by
    nlinarith only [hXI, hfourc]
  have hgram : inner ℝ x y ^ 2 - c ^ 2 * ‖x‖ ^ 2 * ‖y‖ ^ 2 =
      (1 - c ^ 2) * (X ^ 2 + 2 * c * X * Y + 4 * c ^ 2 * P) := by
    rw [hinner, hnormx, hnormy]
    dsimp [X, Y, P]
    ring
  have hproduct := mul_nonpos_of_nonneg_of_nonpos (sub_nonneg.mpr hcsq) hbracket
  have hsq : (-inner ℝ x y) ^ 2 ≤ ((-c) * ‖x‖ * ‖y‖) ^ 2 := by
    nlinarith only [hgram, hproduct]
  have hroot := (sq_le_sq₀ (neg_nonneg.mpr hnegative.le)
    (mul_nonneg (mul_nonneg (neg_nonneg.mpr hc.le) (norm_nonneg x))
      (norm_nonneg y))).mp hsq
  calc
    -r * ‖x‖ * ‖y‖ ≤ c * ‖x‖ * ‖y‖ :=
      mul_le_mul_of_nonneg_right
        (mul_le_mul_of_nonneg_right hcorrelation (norm_nonneg x)) (norm_nonneg y)
    _ ≤ inner ℝ x y := by linarith

/-- The cone bound for actual two-column dictionary synthesis, with a
general nonnegative correlation allowance. -/
theorem two_column_cone_inner_ge {d : ℕ}
    (B : Matrix (Fin d) (Fin 2) ℝ) (hunit : HasUnitEuclideanColumns B)
    (r : ℝ) (hr : 0 ≤ r)
    (hcorrelation : -r ≤ inner ℝ (representationToEuclidean d (B.col 0))
      (representationToEuclidean d (B.col 1)))
    (u v : FeatureVector 2) (hu : ∀ j, 0 ≤ u j) (hv : ∀ j, 0 ≤ v j) :
    -r * ‖representationToEuclidean d (B.mulVec u)‖ *
        ‖representationToEuclidean d (B.mulVec v)‖ ≤
      inner ℝ (representationToEuclidean d (B.mulVec u))
        (representationToEuclidean d (B.mulVec v)) := by
  rw [two_column_euclidean_mulVec, two_column_euclidean_mulVec]
  exact inner_nonnegative_two_generator_combinations_ge _ _ (hunit 0) (hunit 1)
    r hr hcorrelation (u 0) (u 1) (v 0) (v 1) (hu 0) (hu 1) (hv 0) (hv 1)

/-- At decoding margin one half, every pair of vectors in the actual
nonnegative two-column cone has cosine numerator at least minus three
quarters times its norm product. -/
theorem two_column_half_stable_cone_inner_ge {d : ℕ}
    (B : Matrix (Fin d) (Fin 2) ℝ) (hunit : HasUnitEuclideanColumns B)
    (hstable : SparseLowerStable B (1 / 2) 4)
    (u v : FeatureVector 2) (hu : ∀ j, 0 ≤ u j) (hv : ∀ j, 0 ≤ v j) :
    -(3 / 4 : ℝ) * ‖representationToEuclidean d (B.mulVec u)‖ *
        ‖representationToEuclidean d (B.mulVec v)‖ ≤
      inner ℝ (representationToEuclidean d (B.mulVec u))
        (representationToEuclidean d (B.mulVec v)) := by
  have hcorr := (two_column_half_stable_iff_abs_inner_le_three_quarters B hunit).mp hstable
  exact two_column_cone_inner_ge B hunit (3 / 4) (by norm_num) (abs_le.mp hcorr).1 u v hu hv

/-- Nonzero vectors in the stable cone have actual normalized cosine at
least minus three quarters. This is the quotient convention used for the
mesoscale plane obstruction. -/
theorem two_column_half_stable_cone_cosine_ge {d : ℕ}
    (B : Matrix (Fin d) (Fin 2) ℝ) (hunit : HasUnitEuclideanColumns B)
    (hstable : SparseLowerStable B (1 / 2) 4)
    (u v : FeatureVector 2) (hu : ∀ j, 0 ≤ u j) (hv : ∀ j, 0 ≤ v j)
    (hBu : representationToEuclidean d (B.mulVec u) ≠ 0)
    (hBv : representationToEuclidean d (B.mulVec v) ≠ 0) :
    -(3 / 4 : ℝ) ≤
      inner ℝ (representationToEuclidean d (B.mulVec u))
          (representationToEuclidean d (B.mulVec v)) /
        (‖representationToEuclidean d (B.mulVec u)‖ *
          ‖representationToEuclidean d (B.mulVec v)‖) := by
  apply (le_div_iff₀ (mul_pos (norm_pos_iff.mpr hBu) (norm_pos_iff.mpr hBv))).mpr
  simpa only [mul_assoc] using two_column_half_stable_cone_inner_ge B hunit hstable u v hu hv

/-- The equivalent statement with both cone vectors explicitly normalized
to unit length. -/
theorem two_column_half_stable_cone_normalized_inner_ge {d : ℕ}
    (B : Matrix (Fin d) (Fin 2) ℝ) (hunit : HasUnitEuclideanColumns B)
    (hstable : SparseLowerStable B (1 / 2) 4)
    (u v : FeatureVector 2) (hu : ∀ j, 0 ≤ u j) (hv : ∀ j, 0 ≤ v j)
    (hBu : representationToEuclidean d (B.mulVec u) ≠ 0)
    (hBv : representationToEuclidean d (B.mulVec v) ≠ 0) :
    -(3 / 4 : ℝ) ≤
      inner ℝ (NormedSpace.normalize (representationToEuclidean d (B.mulVec u)))
        (NormedSpace.normalize (representationToEuclidean d (B.mulVec v))) := by
  have h := two_column_half_stable_cone_cosine_ge B hunit hstable u v hu hv hBu hBv
  simpa only [NormedSpace.normalize, real_inner_smul_left, real_inner_smul_right,
    div_eq_mul_inv, mul_inv_rev, mul_left_comm, mul_comm, mul_assoc] using h

end PKG26AtomicFeatures
